- setupbase.py
I was a bit too agressive on the `package_data` cleanup. Now re-adding HTML templates.
> Include missing templates in package

- jupyter_server/services/api/tests/test_api.py
- jupyter_server/services/contents/tests/test_contents_api.py
- jupyter_server/services/kernels/handlers.py
- jupyter_server/services/kernels/kernelmanager.py
- jupyter_server/services/kernels/tests/test_kernels_api.py
- jupyter_server/tests/launchserver.py
- jupyter_server/tests/test_files.py
Fixes #17.
To change that parameter: first
```shell
jupyter server --generate-config
```
to generate a configuration file, then change the list of allowed message types.
```python
c.MappingKernelManager.allowed_message_types = ['kernel_info_request']
```
will cause e.g. `execute_request` message to trigger the warning:
"Received message of type "kernel_info_request", which is not allowed. Ignoring."
> WIP - Enable kernel message filtering

- .travis.yml
Upgrade to production Python 3.7 in alignment with travis-ci/travis-ci#9069
> Travis CI: Upgrade from Py37 preresease to production release

- .travis.yml
- jupyter_server/base/zmqhandlers.py
- jupyter_server/utils.py
backport of https://github.com/jupyter/notebook/pull/4449 and https://github.com/jupyter/notebook/pull/4392
resolves #42
> Fix for tornado6

- jupyter_server/base/handlers.py
To mirror the same logic in the [notebook](https://github.com/jupyter/notebook/blob/9560e0cf4c3a3612f7e0f869035e7e3eeb5853a0/notebook/base/handlers.py#L490), this adds localhost to the default list of `local_hostnames`.  Without this, jupyter_server extensions get a 403, unless they set `ServerApp.allow_remote_access = True`.  Instead, the error case on line 430 is hit, stating something like:
```
Blocking request with non-local 'Host' localhost (localhost:52620). If the server should be accessible at that name, set ServerApp.allow_remote_access to disable the check.
```
This fixes it!
> Add localhost to list of default local_hostnames

- jupyter_server/extension/application.py
- jupyter_server/extension/handler.py
This is an initial implementation of a "Jupyter server extension application" class. Pinging @SylvainCorlay @takluyver @kevin-bates @lresende @rolweber @maartenbreddels for review.
This PR introduces the `ExtensionApp` to the Jupyter server, a base class for creating configurable, front-end client applications as extensions of the jupyter server. 
**Details**
`ExtensionApp` subclasses `JupyterApp` from `jupyter_core`. Extensions that subclass this class can be:
* launched and configured from the command line with `jupyter <extension_name> ...`
* configured by a file named `jupyter_<extension_name>_config.py`. 
When an extension application is launched, it
1. starts and launches an instance of the Jupyter server.
2. calls `self.load_jupyter_server_extension()` method.
3. loads …
> [MRG] Configurable server extension applications

- jupyter_server/extension/application.py
- jupyter_server/extension/handler.py
This PR makes it easier to pass extension config/settings to extension handlers. 
Here, extension traits are collected in a `Config` object and added to the jupyter server's webapp settings. Extension handlers can access these settings through its `self.config` property using the `.` notation—e.g. `self.config.some_setting`.
> [MRG] Pass extension configuration to extension handlers

- .travis.yml
- jupyter_server/services/kernels/handlers.py
- setup.py
This PR partially implements requirement of jupyter/jupyter_client#446
This requires jupyter/jupyter_client#447 to be merged first.
> Added control channel to ZMQChannelsHandler

- appveyor.yml
The issue with zeromq 4.2.3 on conda-forge was fixed. We should be able to unpin it.
> Unpin zeromq

- jupyter_server/extension/application.py
- jupyter_server/extension/handler.py
Fixes a bug that was breaking jupyter/notebook#4653.
Passes the `extension_name` arg to *only* handlers that subclass the ExtensionHandler class. This bug was breaking custom static filehandlers in the notebook extension app.
> pass extension_name to only extension app handlers

- jupyter_server/base/handlers.py
- jupyter_server/serverapp.py
The expected behavior of `ServerApp.default_url` is to redirect to (base_url +) `default_url` when the base url (`/`) is requested.
But I think https://github.com/jupyter/jupyter_server/pull/54 broke this by adding a `/` handler. Which seems to prevent the [redirect handler](https://github.com/jupyter/jupyter_server/blob/master/jupyter_server/serverapp.py#L308) from working.
To fix, I propose conditionally setting the root url handler based on whether `default_url` is specified in config.
To reproduce: `jupyter server --ServerApp.default_url='/please_redirect_here' --ServerApp.token='' --ServerApp.open_browser=False`, and navigate to `localhost:8888`.
Note: the `--ServerApp.open_browser=False` option is required, as `open_browser` emulates the redirect logic …
> Fix default_url redirect with default 'main' handler

- jupyter_server/serverapp.py
When investigating https://github.com/jupyter/jupyter_server/pull/72, it was noticed that `--ServerApp.open_browser=True` (the default) did not exhibit the bug. And the browser would open the `default_url` as expected.
This is because the `open_browser` logic effectively redirects to the `default_url` in code.
I propose changing the `open_browser` logic to simply open the `base_url`, and allowing the redirect logic (if specified) to handling redirecting to the `default_url`. Rather than emulating this behavior in code.
> Remove 'coded redirect' to default_url

- jupyter_server/_version.py
- jupyter_server/serverapp.py
- jupyter_server/tests/test_serverapp.py
To help minimize support round trips, this change adds the server's version information into the informational message logged when the server starts in addition to the server-info file that lives while the server is running.
e.g.,
```
[I 13:10:43.541 ServerApp] Jupyter Server 0.2.0.dev0 is running at:
[I 13:10:43.541 ServerApp] http://localhost:8888/?token=57a4f4fa588cec57429981020b02d154b7439788ec274fe9
```
I also took the liberty of incrementing the version for the next dev iteration and added `.dev0` so we can distinguish dev builds from releases.
> List server version in initial log and server-info file

- jupyter_server/extension/application.py
- jupyter_server/extension/handler.py
- jupyter_server/serverapp.py
My alternative solution to #70 and #75. 
This makes standalone mode an option only set by extension authors, not a configurable trait that users can set...
> Standalone mode set by extension authors

- jupyter_server/extension/application.py
- jupyter_server/extension/handler.py
- jupyter_server/serverapp.py
This is one way to implement "standalone" mode #64. 
This adds standalone mode *to the ServerApp* itself (not just extensions). Extensions can then run a standalone server by exposing a flag that sets `ServerApp.standalone=True`.
> Add standalone mode to server

- jupyter_server/serverapp.py
- jupyter_server/tests/test_utils.py
- jupyter_server/utils.py
- setup.py
This follows an advisory suggesting this change be made to help protect the secret files from being exposed to other users on a box running jupyter.
> Added secure_write to function for cookie / token saves

- jupyter_server/utils.py
See https://github.com/jupyter/jupyter_client/pull/478 for details, but this should be included in the next release.
> Applied fix for secure writes in non-enlgish windows that was added to jupyer_client

- .travis.yml
- appveyor.yml
- jupyter_server/auth/login.py
- jupyter_server/base/handlers.py
- jupyter_server/base/zmqhandlers.py
- jupyter_server/files/handlers.py
- jupyter_server/nbconvert/tests/test_nbconvert_handlers.py
- jupyter_server/serverapp.py
- jupyter_server/services/contents/fileio.py
- jupyter_server/services/contents/tests/test_contents_api.py
- jupyter_server/tests/launchserver.py
- jupyter_server/tests/test_extensions.py
- jupyter_server/tests/test_paths.py
- jupyter_server/tests/test_serverapp.py
- jupyter_server/utils.py
- setup.py
Adjust dependencies and conditional imports/functions that distinguished
between Python versions 2 and 3.
I purposely skipped adjusting code like [the following](https://github.com/jupyter/jupyter_server/blob/master/jupyter_server/services/kernels/kernelmanager.py#L189-L190) since that should be part of a general native coroutine sweep (see #93).
```python
raise gen.Return(kernel_id)
```
Closes: #63
> Remove Python 2 support, require 3.5+

- jupyter_server/auth/login.py
- jupyter_server/base/handlers.py
- jupyter_server/serverapp.py
- jupyter_server/services/kernels/handlers.py
For more details about these PRs, see
> [Batch 1] Port Notebook PRs

- jupyter_server/files/handlers.py
- jupyter_server/prometheus/log_functions.py
- jupyter_server/serverapp.py
- jupyter_server/services/contents/handlers.py
- jupyter_server/services/kernels/kernelmanager.py
- jupyter_server/terminal/__init__.py
> [Batch 3] Porting Notebook PRs

- .gitignore
- .travis.yml
- docs/source/examples/Notebook/Running Code.ipynb
- jupyter_server/auth/login.py
- jupyter_server/base/handlers.py
- jupyter_server/serverapp.py
- jupyter_server/services/contents/filemanager.py
- jupyter_server/services/kernels/tests/test_kernels_api.py
- jupyter_server/services/sessions/sessionmanager.py
- jupyter_server/templates/browser-open.html
- jupyter_server/tests/selenium/test_multiselect.py
- jupyter_server/tests/test_serverapp.py
- jupyter_server/tree/tests/handlers.py
- jupyter_server/utils.py
- setup.py
> [Batch 4] Porting Notebook PRs

- docs/source/conf.py
- docs/source/index.rst
Closes #26 
- Rename doc title
- add page directive note about developer preview
> Reduce documentation confusion with stable notebook docs

- jupyter_server/files/handlers.py
- jupyter_server/serverapp.py
> [Batch 6] Porting Notebook PRs

- CONTRIBUTING.rst
- docs/source/extending/contents.rst
- docs/source/public_server.rst
- setup.py
> [Batch 7] Porting Notebook PRs

- jupyter_server/base/handlers.py
- jupyter_server/services/api/tests/test_api.py
- jupyter_server/services/contents/manager.py
- jupyter_server/services/kernels/kernelmanager.py
> [Batch 8] Porting Notebook PRs

- docs/source/public_server.rst
- jupyter_server/gateway/handlers.py
- jupyter_server/gateway/managers.py
- jupyter_server/serverapp.py
- jupyter_server/services/kernels/handlers.py
- jupyter_server/services/kernelspecs/handlers.py
- jupyter_server/services/sessions/sessionmanager.py
- jupyter_server/services/sessions/tests/test_sessionmanager.py
- jupyter_server/tests/launchserver.py
- jupyter_server/tests/test_gateway.py
Ported (cherry-picked) the following Notebook commits to incorporate gateway support into server (Note: commit ids are relative to Notebook [newest to oldest] for cross-referencing):
```
a1b133393 Attempt to re-establish websocket connection to Gateway (#4777)
7e50cdc85 Remove verbose debug statement in gateway mode (#4725)
2339e6fa2 Missing yield statement on WebSocketChannelsHandler (#4724)
eb4285ed5 Add keepalive ping on gateway websocket (#4701)
385dc9ae0 Add authorization token to header only if no authorization already (#4701)
0c4518823 Modify/add various timeout values (#4701)
914a3f070 Fix binary message issue when configured to forward to gateway (#4576)
be35a370c gateway: compatibility with tornado 4 (#4449)
46bcf78d6 Update gateway support with recent changes (#4431)
acba19033 …
```
> Port gateway from notebook

- .travis.yml
- jupyter_server/base/zmqhandlers.py
- jupyter_server/files/handlers.py
- jupyter_server/services/api/handlers.py
- jupyter_server/services/contents/handlers.py
- jupyter_server/services/kernels/handlers.py
- jupyter_server/services/kernels/kernelmanager.py
- jupyter_server/services/kernelspecs/handlers.py
- jupyter_server/services/sessions/handlers.py
- jupyter_server/services/sessions/sessionmanager.py
- jupyter_server/services/sessions/tests/test_sessionmanager.py
- jupyter_server/utils.py
- setup.py
> Port Notebook PRs patching tornado 6

- jupyter_server/base/handlers.py
One of the commits ported from Notebook reverted previous changes to drop support for python 2.
This change is the only known issue stemming from the batched port exercise.
Closes: #96
> Remove python 2 specific code after NB port

- setup.cfg
No need to build a py2.py3 wheel if we don't support py2.  This should have been part of #94.
> Stop building a universal wheel

- jupyter_server/extension/application.py
- jupyter_server/serverapp.py
Three things have changed: 
1. `ExtensionApp` patches the server's browser-open file and open at the extension's `default_url`. This logic only applies when the extension is launched directly (not loaded using the `ServerApp.load_server_extensions()` method). 
2. `ExtensionApp` patches the server's `display_url` (what's shown in the terminal when you launch) by overwriting the `custom_display_url` trait of the server.
3. URLS in the ServerApp are constructed using `urllib`. Provides a cleaner way to construct/deconstruct urls.
> Open ExtensionApps at extension's landing page

- jupyter_server/extension/application.py
- jupyter_server/serverapp.py
Fixing comments from #113. 
@vidartf
> cleaning up PR#113

- jupyter_server/serverapp.py
As @martinRenou argues in https://github.com/voila-dashboards/voila/pull/413 it makes sense to include base_url for this template, so all templates are access to the same variables.
Since we will rely on jupyter_server, it would be nice to keep this feature.
> feat: add base_url to browser_open.html template

- jupyter_server/extension/application.py
Here's my proposed fix for handling subcommands in `ExtensionApp`s. This essentially preparses the command line, looking for any subcommands called from the CLI. 
tl;dr
The problem is that traitlet's `parse_command_line` method both parses the command line *and* loads configuration for the current instance of the `JupyterApp`. The coupling of these two things causes issues for the ExtensionApp, which is a hierarchical chain of `JupyterApp`s. Loading the config before initializing the ServerApp leads to trouble. Preparsing the command line and exiting the current application if a subapp or `--help` flag is present solves the issue. 
@echarles this would replace #125
> [MRG] preparse subcommands in an extensionapps

- .travis.yml
- appveyor.yml
- setup.py
jupyter_kernel_mgmt 0.5.0 has [just been released](https://github.com/takluyver/jupyter_kernel_mgmt/issues/33). It does not run on python 3.5.
This PR enforce a minimum version of 3.6 for Python.
Regarding EOL of 3.5:
- Official [still alive until 2020-09-13](https://devguide.python.org/#status-of-python-branches)
- In practice it seems like all latest standard platforms [don't use 3.5 anymore](https://github.com/python-trio/trio/issues/75#issuecomment-559917654)
- Numpy also recommend [to not support 3.5](https://numpy.org/neps/nep-0029-deprecation_policy.html)
> Enforce Python 3.6 in setup.py to support JKM

- jupyter_server/gateway/managers.py
- jupyter_server/tests/test_gateway.py
`gateway_request` in `gateway.manager` raises `tornado.web.HTTPError` exceptions, but the callers, such as `GatewayKernelManager.get_kernel`, catch `tornado.httpclient.HTTPError`, instead of `tornado.web.HTTPError`. Therefore, the callers can not handle exceptions during gateway interactions.
This causes that, for example, when Jupyter Enterprise Gateway culled a kernel by idle timeout, the gateway manager can not handle the kernel's absent appropriately. As a result, notebook users see ambiguous "Kernel Error" and can not restart the kernel or start a new kernel.
(This is the same as jupyter/notebook#5055.)
> Fix packages of exceptions catched by gateway manager

- .github/workflows/main.yml
- .travis.yml
- appveyor.yml
- setup.py
This is a follow up of https://github.com/jupyter/jupyter_server/pull/142 to renable python 3.5 support in preparation of the 0.2.0 release.
jupyter server 0.3.0 would only support python 3.6.
> Revert back to python 3.5 support

- tests/services/sessions/test_api.py
- tests/services/sessions/test_manager.py
@kevin-bates and @echarles Here are the missing sessions tests left out of #152.
> Add missing sessions test

- jupyter_server/extension/application.py
Addresses #120. 
Adds a trait to `ExtensionApp`s to configure opening browser windows on launch.
> [MRG] add open_browser trait to ExtensionApp

- jupyter_server/serverapp.py
Fixes https://github.com/jupyter/jupyter_server/issues/134
Compare https://github.com/jupyter/notebook/pull/5021 which fixes notebook's #5002 https://github.com/jupyter/notebook/issues/5002
> Fixes #134

- docs/source/extending/handlers.rst
- jupyter_server/serverapp.py
> add notebook_dir as trait to be deprecated

- appveyor.yml
- jupyter_server/pytest_plugin.py
- setup.py
- tests/conftest.py
- tests/extension/conftest.py
- tests/extension/test_entrypoint.py
- tests/extension/test_serverextension.py
- tests/nbconvert/test_handlers.py
- tests/services/contents/test_api.py
- tests/services/contents/test_largefilemanager.py
- tests/services/contents/test_manager.py
- tests/services/kernels/test_api.py
- tests/services/kernelspecs/test_api.py
- tests/services/sessions/test_api.py
- tests/test_files.py
- tests/test_gateway.py
- tests/utils.py
This PR moves the `conftest` into the jupyter_server module and exposes an entrypoint to that module to enable extensions to use these helpful fixtures for testing. 
To use these fixtures, you simply have to add `pytest_jupyter_server` to the `pytest_plugins` list in any test suite.
> Expose a jupyter_server pytest plugin

- README.md
- jupyter_server/_version.py
Adds language around versioning. 
Also bumps master to 0.3.0.dev.
> Add documentation of versioning/branches to main README

- jupyter_server/serverapp.py
Notebook overrides the logger date format to not include the date in
log entries and, as a result, Server followed suit.  Since we expect
Server to run multiple days on end, and the log will typically be
redirected, etc., we should use the default date format - which
includes the date.  As a result, entries will look like the following...
[D 2020-01-13 15:52:01.768 ServerApp] Looking for jupyter_config in /etc/jupyter
> Include date in log statements

- .github/workflows/main.yml
- appveyor.yml
- setup.py
Now that ipykernel 5.1.4 is available and includes the windows/python 3.8 event loop fix, we can drop our workarounds to pull from github.
> Remove win-py38 ipykernel patch

- jupyter_server/extension/application.py
Trying out the [`ExtensionApp` PR in voila](https://github.com/voila-dashboards/voila/pull/492), it looks like the default value for `extension_name` was not picking up `name`.
Also the validation should extract the value from the proposal.
> Fix default extension_name and validation

- jupyter_server/services/api/api.yaml
- jupyter_server/services/kernels/handlers.py
- tests/services/kernels/test_api.py
Allow kernels to be started in a given API `path` even if they are not managed by a session.
This is useful if one is using `jupyter_server` as a limited `kernel` provider but still want to set the `cwd` of the started kernel.
> Allow the path of a kernel to be set in POST

- jupyter_server/extension/application.py
- jupyter_server/pytest_plugin.py
- tests/extension/conftest.py
- tests/extension/test_app.py
- tests/extension/test_entrypoint.py
- tests/extension/test_handler.py
This PR ensures `initialize_templates` is called by `_prepare_templates`.
It also introduce `make_mock_extension_app` fixture to inject the `template_paths` and adds a test for template handler.
> Ensure initialize_templates is called by _prepare_templates 

- jupyter_server/pytest_plugin.py
- tests/services/contents/test_manager.py
- tests/services/kernels/test_api.py
- tests/services/kernelspecs/test_api.py
While reading the tests, I found a few minor enhancements like removing the param from base_url fixture and adding doc to app fixture.\
I may push in the coming day more minore udpates.
My understanding is that only the fixtures defined in `pytest_plugin.py` are usable in other projects (like nbclassic). Then, how do we decide which fixture to expose? e.g. I can see a use of `ws_fetch` defined in `test_api.py` in kernel related projects but today this is not possible.
> Minor enhancements to the fixtures

- docs/source/frontends.rst
- jupyter_server/extension/application.py
- jupyter_server/extension/handler.py
- tests/extension/conftest.py
This is a first dry attempt to support extension handlers needed by JupyterLab https://github.com/jupyterlab/jupyterlab_server/pull/79
The corresponding issue is https://github.com/jupyter/jupyter_server/issues/173
This current changes allow make the jlab extensions operational, but this implementation is suboptimal as it duplicates code (with minor changes) from the base package.
> Make ExtensionHandler a Mixin

- docs/source/frontends.rst
This PR add a simple section in the documentation to invite developers to tag the extension repositories with `jupyter-server-extension`.
> Document tag to use on extension repositories

- setup.py
- setupbase.py
If you install or update `jupyter_server` after [notebook](https://github.com/jupyter/notebook) the executable `jupyter-bundlerextension` will be overwritten because of the entrypoint defined in [setup.py](https://github.com/jupyter/jupyter_server/blob/master/setup.py#L102) and the [conda-forge-recipe](https://github.com/conda-forge/jupyter_server-feedstock/blob/master/recipe/meta.yaml#L18). You will get the following error if you execute the following example command `jupyter bundlerextension list`
```python
File "/Users/USER/opt/anaconda3/bin/jupyter-bundlerextension", line 7, in <module>
from jupyter_server.bundlerextensions import main
ModuleNotFoundError: No module named 'jupyter_server.bundlerextensions'
```
This can be fixed by reinstalling …
> Remove remains of jupyter bundlerextension

- .github/workflows/main.yml
This allows users to ensure their changes can be tested via the CI tools prior to submitting the pull request.
(Unfortunately, it seems the one terminal test on macOS and python 3.7 is failing consistently right now.)
> Trigger github actions on all pushed branches

- CHANGELOG.md
- README.md
- jupyter_server/_version.py
> bump version to 0.3 for minor release

- jupyter_server/prometheus/metrics.py
> Prevent re-definition of prometheus metrics

- jupyter_server/serverapp.py
When checking in serverapp for `load_jupyter_server_extension` or `_load_jupyter_server_extension`, this PR reduces the scope of the except (only catch  AttributeError and not other exceptions as this may hide other issues).
It also logs a warning if `load_jupyter_server_extension` instead of the preferred `_load_jupyter_server_extension`.
> Update log messages when testing for load_jupyter_server_extension method

- jupyter_server/serverapp.py
This is a follow-up of #212 to ensure the try/except is correctly nested and the load_jupyter_server_extension is only called if it exists.
Calling load_jupyter_server_extension is now be outside of any try/except otherwise the server will be started even if it should not (ee.g. load_jupyter_server_extension throwing a AttributeError)
> Nested try/except on _load_jupyter_server_extension discovery

- jupyter_server/extension/application.py
- jupyter_server/serverapp.py
Fixes #211. @davidbrochart 
This PR:
1. separates out the logic that looks at jupyter_config_path to find server extensions.
1. makes `find_server_extensions` a separate step in the server `initialize` method.
1. renames `load_extensions` argument to `find_extension`. 
As a result,
1. If `find_extension=False`, only extensions that are *directly* passed to the ServerApp through CLI, argv, or the `jpserver_extensions` trait will be initialized+loaded. Extensions listed in config files are ignored.
1. ExtensionApps with `load_other_extensions=False` will ignore all other extensions (unless the ExtensionApp explicitly whitelists some extensions through its initialize method).
> Add option to load extensions listed on jupyter_config_path

- docs/source/developers/extensions.rst
I think it would be good to recommend using the `authenticated` decorator in the documentation examples for the extension handlers.
> Add `authenticated` decorator to handlers in doc

- jupyter_server/templates/login.html
- jupyter_server/templates/logout.html
If you try to run a jupyter-server with just basic password it will fail with `500` on the login handler with the error "login.html" not found. 
This PR fixes the error. The code is extracted from jupyter-notebook [login.html](https://github.com/jupyter/notebook/blob/master/notebook/templates/login.html)
> add basic login.html template

- jupyter_server/extension/application.py
This is a fix for https://github.com/jupyter/jupyter_server/issues/215
It uses the ExtensionApp open_browser trait for ServerApp config.
> Use extensionapp open_browser trait for serverapp config

- tests/test_terminal.py
The tests were failing in `test_terminals.py` on CI because terminals opened in one test persisted across other tests. Here, I've added a fixture to kill all terminals after each test. 
This is a work in progress—it doesn't fix the issue yet, but it's a step in the right direction. I can verify on my branch that terminals are staying open between tests.
I'll remove the "Draft" label once I've fixed the issue.
> add fixture to kill all terminals after each test

- jupyter_server/serverapp.py
- setup.py
this is deprecated as of pyzmq 17 (Feb 2018) which is already our minimum version.
> remove call to deprecated pyzmq ioloop.install

- README.md
Fix Jovyan Zoom URL on the README
Was: https://calpoly.zoom.us/my/jupyter
Should be: https://zoom.us/my/jovyan
> Fix Jovyan Zoom URL

- docs/source/developers/rest-api.rst
- docs/source/index.rst
- jupyter_server/services/api/api.yaml
A quick change to:
- Add a link to interactive version of the REST API rendered by swagger
- Update the title of the API spec to "Jupyter Server"
> Add a link to the swagger viewer to the REST API page in the docs

- jupyter_server/extension/application.py
This is a hotfix for a regression introduced in https://github.com/jupyter/jupyter_server/pull/217
As discussed during last jupyter server weekly meeting, open_browser defined on ExtensionApp should be a primitive boolean value, not a trait.
We will review anyway this when we will support serverapp traits overrides in a generic way (with whitelist).
> [HOTFIX] open_browser should be a primitive, not a trait

- .github/workflows/main.yml
- README.md
- jupyter_server/__init__.py
- setup.py
> Fix python<3.7 on windows

- docs/source/developers/extensions.rst
- docs/source/operators/configuring-extensions.rst
- examples/simple/simple_ext1/application.py
- examples/simple/simple_ext1/handlers.py
- examples/simple/simple_ext11/application.py
- examples/simple/simple_ext2/application.py
- jupyter_server/extension/application.py
- jupyter_server/extension/handler.py
- jupyter_server/extension/serverextension.py
- jupyter_server/serverapp.py
- tests/extension/mockextensions/app.py
Changes the `extension_name` trait to `name` in ExtensionApp. 
This addresses issues in #222 and #224. @echarles
> ExtensionApp: change extension_name to name.

- jupyter_server/serverapp.py
as it is, when base_url is set, default_url would redirect to itself, creating an infinite redirect loop.
The condition is meant to prevent this loop when the default_url is the base_url, but base_url's default value was hardcoded in the check, causing the behavior to only be correct when base_url has this default value.
discovered testing with jupyterhub: https://github.com/jupyterhub/jupyterhub/pull/3128
> fix default_url redirect when base_url is defined

- jupyter_server/services/api/handlers.py
- tests/services/api/test_api.py
and make sure status handler is tested
status handler is currently returning 500 because the default KernelManager has a synchronous list_kernels method
This is blocking jupyterhub support for juptyer_server: https://github.com/jupyterhub/jupyterhub/pull/3128
> add ensure_async in status handler

- setup.py
> Drop ipykernel dependency

- jupyter_server/extension/application.py
We should remove the `open_browser` attribute from extensionapp so that applications can override the exposed open_browser set in serverapp_config.
> Remove open_browser attribute from extensionapp

- jupyter_server/extension/application.py
- jupyter_server/extension/handler.py
- jupyter_server/log.py
- jupyter_server/serverapp.py
This enables server extensions to log from their own logger, rather than always logging from the `ServerApp`'s logger. Previously, all log messages from extensions were routed through the ServerApp logger, leading to some confusion on where these messages were actually coming from.
Fixes #273.
> Enable JupyterHandlers to set the logger on log_request

- jupyter_server/extension/manager.py
- tests/extension/test_manager.py
This logic is missing in #248, so I've added it here.
The `linked_extension` property tracks if an extension has already been initialized and linked to a ServerApp. It was originally added for [nbclassic](https://github.com/Zsailer/nbclassic) when handling the shimming of server extensions. (This missing logic hasn't caused any issues because nbclassic is appending extensions directly to the private property, `_linked_extensions`). 
This missing public-facing property became an issue when drafting [jpserver-extension-check](https://github.com/Zsailer/jpserver-extension-check). I want to use this property to verify that extensions are linked properly in those tests.
> Track linked extensions in extension manager

- docs/source/developers/extensions.rst
Minor updates to the docs to use `_jupyter_server_extension_points` instead of `_jupyter_server_extension_paths`.
> update docs to use _jupyter_server_extension_points

- jupyter_server/extension/application.py
- jupyter_server/extension/handler.py
- jupyter_server/extension/serverextension.py
- tests/extension/mockextensions/app.py
- tests/extension/mockextensions/static/mock.txt
- tests/extension/test_handler.py
Fixes #282.
Adds the base_url as a prefix to all extensions URLs, including the static namespaced URLs. 
I've also added a test to check that the static URL is properly prefixed.
> Prefix all extension URLs with base_url (including static)

- examples/simple/README.md
I wasn't sure if I should put this here or in the dev docs. But I didn't see any examples of launching the Jupyter server from the CLI in [there](https://github.com/jupyter/jupyter_server/blob/master/docs/source/developers/extensions.rst) so I thought it could fit better here.
> Document live reloading option

- docs/source/developers/extensions.rst
It was helpful for me to know the type of the `serverapp` arg passed to the `_load_jupyter_server_extension` function, so I added it here as a type annotation.
> Add type annotation to server extension docs

- setup.py
Include all package data in the wheel.
```
$ python setup.py bdist_wheel
...
copying build/lib/jupyter_server/static/favicons/favicon-file.ico -> build/bdist.macosx-10.9-x86_64/wheel/jupyter_server/static/favicons
...
copying build/lib/jupyter_server/i18n/zh_CN/LC_MESSAGES/nbui.po -> build/bdist.macosx-10.9-x86_64/wheel/jupyter_server/i18n/zh_CN/LC_MESSAGES
```
> Include all package data

- jupyter_server/extension/application.py
Fix Jupyter Server for traitlets 5.0
> add HasTraits to mixin class

- .github/workflows/main.yml
- jupyter_server/serverapp.py
- setup.py
- tests/services/kernels/test_config.py
JupyterLab is dropping support for Python 3.5 in 3.0, see also https://numpy.org/neps/nep-0029-deprecation_policy.html
> Drop support for python 3.5

- jupyter_server/extension/serverextension.py
- jupyter_server/services/config/manager.py
This generalizes the `ConfigManager` a bit, so you can point the manager at other config directories (inspired by work happening in JupyterLab config).
Also addressed @vidartf's comment in [#285](https://github.com/jupyter/jupyter_server/pull/285#discussion_r481209490) by using the `write_dir` argument for setting a config write directory and added a docstring.
> make config_dir_name in ConfigManager configurable.

- jupyter_server/extension/handler.py
Some extra cleanup in the `extension` API.
* Make extension handlers use default tornado logger if no logger is found.
* Provide fallback to jupyter_server templates if extension doesn't have a given template.
> ExtensionHandler logger fallback to default logger

- jupyter_server/extension/application.py
- jupyter_server/extension/handler.py
This fixes a bug when serving static content behind a base_url. `urljoin` drops the base_url because of its leading forward slash. Switching to using `url_path_join` from our utils module.
> replace urljoin with url_path_join in extensionapp

- CHANGELOG.md
- jupyter_server/terminal/__init__.py
- jupyter_server/terminal/handlers.py
- tests/test_terminal.py
#313 removed too much to nbclassic. Reverting part of it allows JupyterLab to work with the standalone jupyter server (and JupyterLab examples to work without loading other extensions like nbclassic).
> Add TermSocket back from nbclassic 

- MANIFEST.in
api.yaml is missing from 1.0.4, resulting in 404s on `/api/api.yaml`, but I don't think there are any files in here we want to exclude. This is causing test failures with jupyterhub + jupyter_server 1.0.4 which uses api.yaml as a test target
explicit excludes can be added if there are known things to exclude
> include eveything in the package directory in package_data

- docs/source/developers/extensions.rst
- jupyter_server/extension/application.py
While working on JupyterLab + Jupyter Server integration, I found that we can make the (new) ExtensionApp work with the old Jupyter Notebook server with this slim chunk of boilerplate code. I suspect that this might be helpful for other applications looking to transition to Jupyter Server. This chunk handles redirects needed, since some static files have moved between Notebook Server and Jupyter Server.
I've also added a short section to the documentation to highlight this useful function.
> Enable ExtensionApps to work with classic notebook server

- .gitignore
- jupyter_server/serverapp.py
Python <3.8 doesn't know how to guess the `.wasm` mimetype, and the browsers are _real particular_ about it. This PR just adds it to the existing patches, without any complicated version detecting. I started writing a test, and ran into some cross-device nonsense, but upon reflection, decided it's probably not worth it. :stuck_out_tongue_closed_eyes: 
As the community starts ramping up cool, complex things that use wasm for various nefarious purposes, this will avoid extensions having to do their own patches.
> Add wasm mime override

- docs/source/developers/extensions.rst
I've added a section to the "Developer" documentation describing the minimal steps needed to migrate a classic Notebook Server extension to Jupyter Server.
> Documentation for migrating server extensions

- jupyter_server/services/kernels/handlers.py
- jupyter_server/services/kernels/kernelmanager.py
Showing a traceback can be a security risk in a context such as Voila.
(for instance showing paths, usernames or values in the exception message)
Similar to what we do at notebook execution time at:
https://github.com/voila-dashboards/voila/pull/758
here we also disable the transfer of tracebacks at runtime.
cc @SylvainCorlay @mariobuikhuizen
> feat: add option to replace traceback on errors

- .github/workflows/codeql-analysis.yml
This will help track down issues like unused imports, etc. See https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning-for-a-repository
Results at https://github.com/jupyter/jupyter_server/security/code-scanning?query=tool%3ACodeQL+is%3Aopen+ref%3Arefs%2Fpull%2F332%2Fmerge
> Scan with CodeQL

- docs/source/other/full-config.rst
- jupyter_server/serverapp.py
This fixes https://github.com/jupyterlab/jupyterlab/issues/8188
> Make the help for quit_button more generic.

- setup.py
- tests/conftest.py
- tests/extension/conftest.py
- tests/extension/test_app.py
- tests/extension/test_config.py
- tests/extension/test_entrypoint.py
- tests/extension/test_handler.py
- tests/extension/test_manager.py
- tests/extension/test_serverextension.py
- tests/extension/test_utils.py
- tests/nbconvert/test_handlers.py
- tests/services/api/test_api.py
- tests/services/config/test_api.py
- tests/services/contents/test_api.py
- tests/services/contents/test_config.py
- tests/services/contents/test_fileio.py
- tests/services/contents/test_largefilemanager.py
- tests/services/contents/test_manager.py
- tests/services/kernels/test_api.py
- tests/services/kernels/test_config.py
- tests/services/kernelspecs/test_api.py
- tests/services/nbconvert/test_api.py
- tests/services/sessions/test_api.py
- tests/test_files.py
- tests/test_gateway.py
- tests/test_serverapp.py
- tests/test_terminal.py
- tests/test_version.py
Now that `pytest-jupyter` is released, this updates the custom fixtures to use their `jp_` versions made available via `pytest-jupyter`.  This will avoid collisions with similarly named fixtures introduced in other packages (provided of course, they too are not prefixed with `jp_` :smile:  ).
Note that because other packages still depend on [`jupyter_server/pytest_plugin.py`](https://github.com/jupyter/jupyter_server/blob/master/jupyter_server/pytest_plugin.py) for the non-prefixed features, both it as well as the [`pytest_jupyter_server`](https://github.com/jupyter/jupyter_server/blob/master/setup.py#L65) entrypoint remain in existence. 
Prior to removing `jupyter_server/pytest_plugin.py` and the `pytest_jupyter_server` entrypoint, we may want to cut a release to provide dependents a …
> Switch fixtures to use those in pytest-jupyter to avoid collisions

- jupyter_server/gateway/handlers.py
This was already merged on jupyter/notebook:
https://github.com/jupyter/notebook/blob/cd7a06ce88387b70c3dbe1bca6ab5ae222e28c60/notebook/gateway/handlers.py#L35
It makes sure the Websocket handler of the Gateway respects the user config of allow_origin.
Happy to change anything if this is not correct/desired for the jupyter_server repo!
> add check_origin handler to gateway WebSocketChannelsHandler

- jupyter_server/gateway/managers.py
- tests/test_gateway.py
This pull request brings over the changes relative to the following Notebook PRs:
- https://github.com/jupyter/notebook/pull/5317: Gateway only: Ensure launch and request timeouts are in sync 
- https://github.com/jupyter/notebook/pull/5484: Added functionality to allow filter kernels by Jupyter Enterprise Gat…
> Port gateway updates from notebook (PRs 5317 and 5484)

- CHANGELOG.md
- docs/source/other/changelog.rst
- jupyter_server/_version.py
- tests/test_paths.py
This applies CVE-2020-26232 to the master branch - already released in jupyter_server 1.0.6.
> Apply security advisory fix to master

- tests/test_paths.py
The trailing_slash_test's merge to master introduced a bit of a chicken/egg issue since it came from a branch that didn't use the updated fixtures now derived from `pytest-jupyter`.  This addresses those issues.
> Fix test_trailing_slash 

- MANIFEST.in
This backports d925e670e0a904a8b75d2412056b951e924bc2c7 to pick up favicons and other files in the package distribution.
> recursive-include to grab spec.yaml and favicons

- jupyter_server/gateway/handlers.py
This PR should fix an issue with the gateway handler introduced by the switch to native async function for the `_connect` function in the gateway websocket handler (which originally used the @gen coroutine version from `tornado`).
`_connect` should now be properly awaited through IOLoop's `spawn_callback` mechanism.
@kevin-bates recommended a PR based on this discussion https://github.com/jupyter/enterprise_gateway/issues/903.
> Await _connect and inline read_messages callback to _connect

- jupyter_server/terminal/__init__.py
This PR brings the commits associated with Notebook PRs https://github.com/jupyter/notebook/pull/5565 and https://github.com/jupyter/notebook/pull/5588.  Originally, we just recorded the need to port 5565, but 5588 was the final outcome.
We can then look at addressing #342 following this update.
> Port Notebook PRs 5565 and 5588 - terminal shell heuristics

- jupyter_server/base/handlers.py
- jupyter_server/serverapp.py
Equivalent to https://github.com/jupyterhub/jupyterhub/pull/2224.
Port of https://github.com/jupyter/notebook/pull/5870
Prometheus metrics can potentially leak information about
the user, so they should be kept behind auth by default.
However, for many JupyterHub deployments, they would need
to be scraped by a centralized Prometheus instance that can not
really authenticate separately to each user notebook without
a lot of work. Admins can use this setting to allow unauthenticated
access to the /metrics endpoint.
> Allow toggling auth for prometheus metrics

- .github/workflows/codeql-analysis.yml
Enable CodeQL on pushed branches so pull request authors have a chance to address flagged issues prior to creating their pull request.
> Enable CodeQL runs on all pushed branches

- .github/workflows/main.yml
The "Upgrade Packaging Dependencies" step in `workflows/main.yml` failed  due to 
```
ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-uninstall-z_gzya01\\pip.exe'
Consider using the `--user` option or check the permissions.
```
The fix is to include the `--user` option.
> Fix upgrade packaging dependencies build step

- examples/simple/setup.py
- examples/simple/tests/conftest.py
- jupyter_server/pytest_plugin.py
- setup.py
- tests/conftest.py
- tests/extension/test_handler.py
- tests/extension/test_serverextension.py
- tests/services/contents/test_api.py
- tests/services/kernels/test_api.py
- tests/services/kernelspecs/test_api.py
- tests/services/sessions/test_api.py
- tests/test_paths.py
- tests/utils.py
In today's [Jupyter Server meeting](https://github.com/jupyter-server/team-compass/issues/1#issuecomment-742705421), we discussed deprecating the pytest-jupyter library and moving (back) to a native pytest_plugin in this package (how we originally had it). 
The pytest-jupyter library introduced extra complexity, requiring us to coordinate releases of pytest-jupyter and jupyter_server anytime there was a change in jupyter_server. 
Here, the pytest_plugin is a submodule in jupyter_server. To use this plugin in a given test suite, add `jupyter_server.pytest_plugin` to the pytest_plugin list of the root `conftest.py` file, e.g.:
```python
pytest_plugin = [
"jupyter_server.pytest_plugin",
...
]
```
This PR includes some fixtures that we should eventually move to the `jupyter_core` package as a …
> Restore pytest plugin from pytest-jupyter

- docs/source/developers/contents.rst
- docs/source/other/full-config.rst
- jupyter_server/base/handlers.py
- jupyter_server/files/handlers.py
- jupyter_server/nbconvert/handlers.py
- jupyter_server/pytest_plugin.py
- jupyter_server/serverapp.py
- jupyter_server/services/contents/checkpoints.py
- jupyter_server/services/contents/filecheckpoints.py
- jupyter_server/services/contents/fileio.py
- jupyter_server/services/contents/filemanager.py
- jupyter_server/services/contents/handlers.py
- jupyter_server/services/contents/largefilemanager.py
- jupyter_server/services/contents/manager.py
- jupyter_server/view/handlers.py
- setup.py
- tests/services/contents/test_api.py
- tests/services/contents/test_config.py
- tests/services/contents/test_largefilemanager.py
- tests/services/contents/test_manager.py
- tests/services/kernels/test_api.py
- tests/services/sessions/test_api.py
**Description**
Hi, here's the draft for adding an async option for the contents api. 
So far, I added an async option for each class/mixin below:
- `ContentsManager` and `AsyncContentsManager`
- `Checkpoints` and `AsyncCheckpoints`
- `GenericCheckpointsMixin` and `AsyncGenericCheckpointsMixin`
@kevin-bates and/or @Zsailer I'd appreciate your review and feedback!
**Open Questions**
I added a test for the configuration, but how do we want to test the new classes since most methods are not implemented and left up to the user?
**Checklist**
> Asynchronous Contents API

- jupyter_server/services/contents/handlers.py
When a custom contents manager is a sub class of `AsyncContentsManager`, and the `dir_exists` method is asynchronous, `dir_exists` is never await during file creation in the specified path. 
**Steps to reproduce error**
1. Run the server with a custom async contents manager that has an asynchronous `dir_exists` method. 
2. Create a notebook
```
RuntimeWarning: coroutine 'AsyncCustomContentsManager.dir_exists' was never awaited
```
> Fix: await possible async dir_exists method

- jupyter_server/services/kernels/handlers.py
Porting https://github.com/jupyter/notebook/pull/5908 to jupyter_server.
see original discussion in jupyter/jupyter_client#593
Nudge kernel with info request upon opening websocket and upon restart until some IOPub message is received.
> Nudge kernel with info request until we receive IOPub messages

- .github/workflows/python-linux.yml
- .github/workflows/python-macos.yml
- .github/workflows/python-windows.yml
- jupyter_server/services/kernels/kernelmanager.py
- tests/services/contents/test_api.py
- tests/services/kernels/test_api.py
- tests/services/kernels/test_cull.py
- tests/services/sessions/test_api.py
Port of https://github.com/jupyter/notebook/pull/5355
Also fixes a race condition in async kernel shutdown and fixes a couple of fixture names that needed a `jp_` prefix.
> Culling: ensure last_activity attr exists before use

- docs/source/developers/extensions.rst
The old one: https://jupyter.readthedocs.io/en/latest/projects/jupyter-directories.html appears dead, but: https://jupyter.readthedocs.io/en/latest/use/jupyter-directories.html works fine.
> Update the link to paths documentation

- setup.py
- setupbase.py
This:
- removes the confusing, deprecated `find_packages` from `setupbase.py`
- imports and uses the _real_ `setuptools.find_packages` to `exclude` things that _might_ be python-module-like
In `site-packages/`, `tests/`, `docs/`, etc. are dumping grounds of all the packages that either _don't_ use this flag. In this state, it's not even worth distributing them, as there's basically zero chance they'll work. Putting them in-tree, on the other hand, is very nice, as downstreams can ensure that their packages work, which helps catch issues sooner, but that's for another day...
> use setuptools find_packages, exclude tests, docs and examples from dist

- jupyter_server/services/contents/handlers.py
- tests/services/contents/test_api.py
Fixes #372.
~Blind edit via web, so not tested yet. I'll see if I can add a regression test as well.~
> Make trust handle use ensure_async

- jupyter_server/extension/application.py
- jupyter_server/serverapp.py
This adds a configurable `open_browser` trait to `ExtensionApp`s, and refactors the `ServerApp` to handle browser-opening properly when another app, e.g. an `ExtensionApp`, starts the server.
This also adds a property, `starter_app`, to `ServerApp` that enables the `ServerApp` to know when an extension started the app (versus starting the server directly).
This will help address this issue seen in JupyterLab: jupyterlab/jupyterlab_server#145
A follow up PR in JupyterLab is needed to use this new trait.
> Handle open_browser trait in ServerApp and ExtensionApp differently

- jupyter_server/serverapp.py
Port of jupyter/notebook#4893 and jupyter/notebook#5075
> Improve Handling of the soft limit on open file handles

- jupyter_server/extension/application.py
- jupyter_server/serverapp.py
Configures both the ServerApp and Extension App when `--debug` and `--no-browser` is used.
This also fixes a minor issue when setting the `_starter_app` in `ServerApp`, that was causing JupyterLab's `LabHubApp` to fail.
> Enable extensions to set debug and open-browser flags

- jupyter_server/serverapp.py
Port of jupyter/notebook#4795. Fixes jupyterlab/nbclassic#39
> Add --autoreload flag

- jupyter_server/base/handlers.py
- jupyter_server/serverapp.py
- jupyter_server/services/contents/filemanager.py
- jupyter_server/services/kernels/kernelmanager.py
- jupyter_server/utils.py
- tests/test_utils.py
There was a time when we found many file-system oriented methods replicated in the ecosystem.  Since then, many have found homes in `jupyter_core`.  This PR removes the duplicated implementations and uses those defined in jupyter_core.
Resolves #381
> Replace secure_write, is_hidden, exists with jupyter_core's

- jupyter_server/services/sessions/handlers.py
While migrating Enterprise Gateway from using notebook to jupyter_server, I ran across a couple of methods in the session handler that needed `ensure_async` wrappers around their calls to the session manager.
> Apply missing ensure_async to root session handler methods

- tests/services/kernels/test_cull.py
This is a port of https://github.com/jupyter/notebook/pull/5952 to increase the kernel idle timeout for the culling test.  Since there was already an increased timeout for 'PyPy', I kept that value (10) in place, although I suspect the new value (5) would be sufficient.
> Increase culling test idle timeout

- jupyter_server/auth/login.py
Use `jupyter_server_config.jso`n instead of `jupyter_notebook_config.json` as config file in the update password API.
> Use jupyter_server_config.json as config file in the update password api

- jupyter_server/extension/application.py
This addresses issues we're seeing in JupyterLab, e.g. jupyterlab/jupyterlab#8959
ExtensionApp was missing a configurable `default_url` trait.
> Re-enable default_url in ExtensionApp

- .github/workflows/python-windows.yml
- jupyter_server/serverapp.py
- jupyter_server/services/sessions/sessionmanager.py
- jupyter_server/traittypes.py
- tests/test_traittypes.py
jupyter_server's `contents_manager_class` doesn't accept subclasses of notebook's `ContentsManager`. While this is the desired behavior for the future of jupyter_server, during this transition phase from notebook to jupyter_server, we should allow notebook's ContentManagers to pass through.
This PR relaxes the `contents_manager_class` to allow these managers. To do this, new `traittypes` are defined and used that check the incoming types/instances against a list of classes.
> Enable notebook ContentsManager in jupyter_server

- jupyter_server/serverapp.py
if an existing jupyter_notebook_config file sets notebook_dir, this would override explicit setting of root_dir, as the deprecated value was used even when the new value was also set.
To simulate, you can try:
jupyter lab . --NotebookApp.notebook_dir=/tmp
> only use deprecated notebook_dir config if root_dir is not set

- jupyter_server/gateway/managers.py
- jupyter_server/serverapp.py
Seems time we switched to using the async kernel management framework by default.  This has already been adopted by NBclient (Papermill), Voila, and Enterprise Gateway.
> Use async kernel manager by default

- CHANGELOG.md
As @jtpio correctly points [here](https://github.com/jupyter-server/jupyter_server/commit/f15749d51a577b6c9a8aa488797ef0354d0db9ff#r46779489), we should update the 1.3.0 changelog contents to include the PRs from the broken 1.2.3 release.  I chose to just duplicate the entries, leaving 1.2.3 as-is for history.
> Update 1.3.0 Changelog to include broken 1.2.3 PRs

- jupyter_server/pytest_plugin.py
With the minimum version bump to Tornado 6.1, we should no longer be using the patch in our fixtures.  This update removes that fixture, as well as the update to the io_loop fixture needed to enable the patch.
> Remove obsoleted asyncio-patch fixture

- jupyter_server/extension/utils.py
Reading that piece of code - I think the log message is at the wrong place.
I also change it to a warning as extension authors should be aware that they should update the method name. Otherwise they would be kept in the dark like I was before today.
> Correct logging message position

- jupyter_server/templates/view.html
- tests/test_view.py
and test coverage to exercise it
server has the view handler, but not the template it relies on.
view.html is copied from notebook 6.2
currently, any visit to `/view/...` will 500 due to this missing template.
> add missing template for view.html

- jupyter_server/extension/application.py
- jupyter_server/pytest_plugin.py
- jupyter_server/serverapp.py
- tests/test_serverapp.py
In classic notebook, users could open a file directly, e.g.:
```
jupyter notebook mynotebook.ipynb
```
The server would start at the parent directory of `mynotebook.ipynb `and open the browser at `/<base_url>/notebook/mynotebook.ipynb`. Alternatively, users could get the same behavior using the `--NotebookApp.file_to_run` trait.
Jupyter server still has the `file_to_run` trait, but the `<base_url>/notebook` prefix is hard-coded, even though it doesn't make sense for server anymore. Further, extensions like JupyterLab cannot easily override this prefix.
This PR adds a new configurable trait, `file_url_prefix`, to both `ServerApp` and `ExtensionApp`. It changes the URL prefix where the server starts when a file_to_run is given. ExtensionApp can define their own `file_url_prefix` default …
> Enable extensions to control the file_to_run

- jupyter_server/gateway/managers.py
- jupyter_server/services/kernels/handlers.py
While working on Enterprise Gateway, I found that if a gateway server is hosting kernels from multiple lab servers (via either jupyter_server or notebook), all kernels managed by the gateway server could be shut down when terminating _one_ of the lab servers.  This change ensures that kernel-based operations of a given lab/notebook server only operate against its own kernels.
Also:
- Updated log statements to f-strings in the working file.
- Found the KernelHandlers `get` method hadn't transitioned to `async def` so I made that change.
> [Gateway] Track only this server's kernels

- jupyter_server/extension/utils.py
Add a deprecation warning on `load_jupyter_server_extension`
> Emit deprecation warning on old name

- jupyter_server/extension/manager.py
Warning message are descriptive when an extension fails to load. To provide an example, before this tiny fix, I got the warning message when starting jupyter-lab:
```[W 2021-01-29 16:36:12.766 ServerApp] 'nbextensions_path'```
while now I would get:
```[W 2021-01-29 16:55:35.576 ServerApp] jupyter_nbextensions_configurator | extension failed loading with message: 'nbextensions_path'```
clarifying that it is `jupyter_nbextensions_configurator` not loading. With this better description, this warning is no more surprising because I know that this extension is for the classic notebook only.
> Update manager.py: more descriptive warnings when extensions fail to load

- jupyter_server/serverapp.py
Python's scoping rules cause the log statement to fail because `_` was being redefined in `launch_browser()`.
The issue was introduced in [this commit](https://github.com/jupyter-server/jupyter_server/commit/1bbcbcb359601f6b0a9e1afd16720df09920aa64#annotation_1006253621) and flagged by CI.
I can confirm that this bug causes JupyterLab to crash when it cannot find a web browser.
> Solve UnboundLocalError in launch_browser()

- CHANGELOG.md
The latest release was 1.4.1, not 1.5.0. The latest entry in the changelog reports the wrong version.
> Correction in Changelog

- jupyter_server/extension/application.py
- jupyter_server/i18n/README.md
- jupyter_server/serverapp.py
- jupyter_server/services/contents/filemanager.py
- jupyter_server/services/contents/manager.py
- jupyter_server/transutils.py
Corresponds to https://github.com/jupyter-server/jupyter_server/issues/424
In this project, `_` is used as an alias for `trans.gettext` although `_` is commonly used as a placeholder for ignored variables or loop variables in Python.
In this PR, I'm trying to rename `_` to `_i18n` as discussed in #424, it would be clearer and more useful to avoid conflicts between these two uses.
P.S.
This is the first time for me to make a contribution, so I would appreciate it if you could kindly point out any inadequacies/advice 😉
> Rename translation function alias

- .github/workflows/python-linux.yml
- .github/workflows/python-macos.yml
- .github/workflows/python-windows.yml
- README.md
- jupyter_server/extension/application.py
- jupyter_server/pytest_plugin.py
- jupyter_server/tests/extension/conftest.py
- jupyter_server/tests/extension/mockextensions/app.py
- jupyter_server/tests/extension/test_app.py
- pytest.ini
This changes the default value open_browser in extension applications slightly.
Before this was set to `True` *always*. That means, even if `ServerApp.open_browser=False`, a browser was still opened. Now, the extension first checks if the server's `open_browser` trait was configured. If so, it uses this configured value; otherwise, it defaults to `True`.
In the case where *both* the starting extension application and the underlying server application receive a configuration value for `open_browser`, the extension application wins as you'd expect.
This PR also drops the `--pyargs` config from `pytest.ini` because it prevents you from running individual tests (always runs the whole test suite). Instead, it is advised to run `pytest <path to tests>`. Updated the README and GA workflows to …
> More complex handling of open_browser from extension applications

- jupyter_server/utils.py
Partial Fix for jupyter-server/jupyter_server#439
This will allow us to see what the actual underlying error is when it happens again.
> Fix for UnboundLocalError in shutdown

- docs/environment.yml
- jupyter_server/serverapp.py
- jupyter_server/services/api/api.yaml
- jupyter_server/terminal/__init__.py
- jupyter_server/terminal/api_handlers.py
- jupyter_server/terminal/handlers.py
- jupyter_server/terminal/terminalmanager.py
- jupyter_server/tests/test_terminal.py
This PR brings from notebook the following PRs to enable the culling of terminals:
- Add ability to cull terminals and track last activity (https://github.com/jupyter/notebook/pull/5372)
- Install terminado for docs build (https://github.com/jupyter/notebook/pull/5462)
- Restore detection of missing terminado package (https://github.com/jupyter/notebook/pull/5465)
Resolves #432
(Note: I was seeing intermittent CI failures in CI-setup and post-test phases (install examples).  All failures were related to python installation issues and it felt like a repository was down or some kind of update was occurring since the issue would move around.  Since these shouldn't be related, I'm moving forward with submitting the PR.)
> Port terminal culling from Notebook

- README.md
Follow up to https://github.com/jupyter-server/jupyter_server/pull/443 to point to https://github.com/jupyter-server/jupyter_server/actions?query=branch%3Amaster++
> Update the branch filter for the CI badge

- examples/simple/simple_ext1/handlers.py
- examples/simple/simple_ext2/handlers.py
- jupyter_server/services/contents/handlers.py
This change runs user-input received as an argument on a few handlers through `url_escape`.  These instances had been flagged by the code analysis CI.
Resolves #447
> Escape user input in handlers flagged during code scans

- jupyter_server/auth/security.py
- jupyter_server/tests/auth/test_security.py
- setup.py
Backport of jupyter/notebook#3793
cf jupyter-server/jupyter_server#110
> Implement password hashing with argon2-cffi

- .gitignore
- CONTRIBUTING.rst
- jupyter_server/static/style/index.css
- jupyter_server/templates/browser-open.html
- jupyter_server/templates/error.html
- jupyter_server/templates/login.html
- jupyter_server/templates/logout.html
- jupyter_server/templates/main.html
- jupyter_server/templates/page.html
- jupyter_server/templates/view.html
- package-lock.json
- package.json
- setup.py
Fixes https://github.com/jupyter-server/jupyter_server/issues/271
Copies more the templates and styling from `notebook`, including the use of `bootstrap`.
Including `bootstrap` adds an `npm` build step and brings the package from 275kB to 405kB.
> Add Styling to the HTML Pages

- jupyter_server/services/contents/manager.py
currently, all errors in pre_save_hook are caught and logged, making it impossible for pre_save_hook to be used for validation / quota enforcement / etc.
By allowing HTTPErrors to raise, save will be cancelled and the hook's error message will be shown to the user in a dialog.
For example:
```python
from tornado.web import HTTPError
def fail_save_forbidden(model, path, **kw):
if "forbidden" in path.split("/"):
raise HTTPError(400, "Can't save forbidden files!")
c.ContentsManager.pre_save_hook = fail_save_forbidden
```
Brought up on [the forum](https://discourse.jupyter.org/t/exit-abort-save-from-pre-save-hook/8410)
> allow pre_save_hook to cancel save with HTTPError

- jupyter_server/services/kernels/kernelmanager.py
This should bring it in line with the signature of the base class (added in jupyter_client 4.0.0).
Fixes #402.
> Update MappingKM.restart_kernel to accept now kwarg

- jupyter_server/serverapp.py
Backport of https://github.com/jupyter/notebook/pull/5136
cf https://github.com/jupyter-server/jupyter_server/issues/110
> Add descriptive log for port unavailable and port-retries=0

- jupyter_server/serverapp.py
Before this PR, the default output of server urls looks like:
Or copy and paste one of these URLs:
http://localhost:8888/?token=…
or http://127.0.0.1:8888/?token=…
This makes it easy to triple-click on the first line to copy and paste it into a browser. However, triple-clicking on the second line picks up the extra “or”, so you can’t just copy and paste it into the browser. Instead, you have to explicitly select each character by dragging your mouse, avoiding the “or”.
This change deletes the “or” so you can just triple-click on the second line to copy and paste the url.
> Delete the extra “or” that prevents easy cut-and-paste of URLs.

- jupyter_server/serverapp.py
- jupyter_server/tests/extension/test_launch.py
Backport of https://github.com/jupyter/notebook/pull/5587
cf. https://github.com/jupyter-server/jupyter_server/issues/110
> Add support for JUPYTER_TOKEN_FILE

- jupyter_server/serverapp.py
Backport of https://github.com/jupyter/notebook/pull/5221
cf https://github.com/jupyter-server/jupyter_server/issues/110
> Add env variable support for port options

- jupyter_server/services/api/api.yaml
Update the following description for the `restart` endpoint:
> Update description for kernel restarted in the API docs

- jupyter_server/__main__.py
- jupyter_server/_sysinfo.py
- jupyter_server/utils.py
Backport of jupyter/notebook#5805
cf jupyter-server/jupyter_server#110
> Remove unnecessary future imports

- .gitignore
- docs/doc-requirements.txt
- docs/environment.yml
- docs/source/conf.py
- docs/source/developers/contents.rst
- docs/source/other/full-config.rst
- docs/source/other/index.rst
- Copy the changelog into the docs source when building
- Use the MyST parser for markdown files
- Clean up docs requirements files
> Add Changelog to Sphinx Docs

- docs/environment.yml
- readthedocs.yml
Builds are failing due to installing with `python setup.py install`, so enforce `pip install .`
> Add ReadTheDocs config

- jupyter_server/services/kernels/kernelmanager.py
Port of https://github.com/jupyter/notebook/pull/5875
cf https://github.com/jupyter-server/jupyter_server/issues/110
> Fix race condition with async kernel management

- jupyter_server/services/kernels/kernelmanager.py
This should fix the errors in #473 (https://github.com/jupyter-server/jupyter_server/pull/473/checks?check_run_id=2323090792#step:14:342), but this is not addressing the real root cause.
> Fix kernel lookup

- jupyter_server/base/handlers.py
- jupyter_server/files/handlers.py
- jupyter_server/nbconvert/handlers.py
Port of https://github.com/jupyter/notebook/pull/5898/files#L395 and associated commits:
- https://github.com/jupyter/notebook/commit/98773c1a8a2eb2e12fbcf1a08fc97e6802f45210 
- https://github.com/jupyter/notebook/commit/d7becafd593c2958d8a241928412ddf4ba801a42
- https://github.com/jupyter/notebook/commit/7f7bfeefc08568aacd626438e22a6361aa57223a 
cf https://github.com/jupyter-server/jupyter_server/issues/110
> Tighten xsrf checks

- jupyter_server/services/kernels/handlers.py
- jupyter_server/services/kernels/kernelmanager.py
- jupyter_server/tests/services/sessions/test_api.py
This change adds the ability for the `ZMQChannelsHandler` and activity watching logic to determine if ports have changed when restoring connections and restarting kernels, respectively.  
By determining that ports have changed during restarts, the `MappingKernelManager` can also restart the activity monitor since it listens on the iopub channel.  This will preserve proper functionality for culling behaviors as well as allow the "nudge" functionality to determine the kernel is busy - bypassing the time-based attempts to send/recieve a kernel-info request.
`ZMQChannelsHandler.open()` makes use of the fact that the kernel's ports have changed when _restoring_ a connection (which essentially consists of loading state from previously recorded buffers).  Prior to this change, the nudge …
> Fix activity tracking and nudge issues when kernel ports change on restarts

- jupyter_server/extension/application.py
- jupyter_server/tests/extension/mockextensions/app.py
- jupyter_server/tests/extension/test_app.py
Prior to this change, an extension app either had to load all all extensions using `load_other_extensions`, or else only load itself.  This change allows an extension app to declare a set of sibling extensions to load using `serverapp_config`.
> Fix loading of sibling extensions

- jupyter_server/base/handlers.py
- jupyter_server/serverapp.py
- jupyter_server/services/config/handlers.py
- jupyter_server/services/contents/filecheckpoints.py
- jupyter_server/services/contents/fileio.py
- jupyter_server/services/contents/filemanager.py
- jupyter_server/services/contents/manager.py
- jupyter_server/services/kernels/kernelmanager.py
- jupyter_server/services/sessions/sessionmanager.py
- jupyter_server/tests/nbconvert/test_handlers.py
- jupyter_server/tests/test_gateway.py
- jupyter_server/utils.py
ipython_genutils is complicated to package on some linux distro because
of nose, and in general not useful as it mostly offered python 2/3
compat layer.
Goal always has been to remove any usage of ipython_genutils
> Remove some of ipython_genutils no-op.

- jupyter_server/_sysinfo.py
- jupyter_server/_tz.py
- jupyter_server/auth/login.py
- jupyter_server/base/zmqhandlers.py
- jupyter_server/extension/serverextension.py
- jupyter_server/gateway/managers.py
- jupyter_server/serverapp.py
- jupyter_server/services/contents/checkpoints.py
- jupyter_server/services/contents/fileio.py
- jupyter_server/services/contents/manager.py
- jupyter_server/services/kernels/kernelmanager.py
- jupyter_server/tests/services/sessions/test_api.py
- jupyter_server/utils.py
This uses an autoreformatter to reformat and fix some of the common
mistakes in numpydoc.
Some of this is purely visual, but other like space before colon in
parameters actually have semantic values. In the case of space before
colon this is to make sure that nupmydoc properly distinguish the
parameter name from its type.
> DOC: Autoreformat docstrings.

- .github/workflows/check-release.yml
- .github/workflows/python-linux.yml
- CHANGELOG.md
- MANIFEST.in
- RELEASE.md
cf jupyter-server/jupyter_releaser#3
> Prep for Release Helper Usage

- jupyter_server/services/contents/filemanager.py
- jupyter_server/tests/services/contents/test_manager.py
This change also prevents permission-related exceptions from logging the file.
Resolves #495
> Fix for recursive symlink - (port Notebook 4670)

- CHANGELOG.md
Automated Changelog Entry for 1.7.0a0 on master
Python version: 1.7.0a0
After merging this PR run the "Draft Release" Workflow with the following inputs
| Version Spec | 1.7.0a0 |
> Automated Changelog Entry for 1.7.0a0 on master

- jupyter_server/extension/manager.py
- jupyter_server/extension/serverextension.py
- jupyter_server/tests/extension/test_manager.py
Related to #500, but doesn't actually fix the main issue there (failure to identify extensions that are not importable).
Current situation:
- ExtensionPoint.validate always returns a falsy value (None or False)
- ExtensionPackage only checks the falsiness, which means it always returns False
- ListServerExtensionApp never checked validate return value, meaning all extensions were always considered valid, even though all extensions actually self-reported as invalid
This fixes:
- ExtensionPoint.validate returns True on successful validation
- ListServerExtensionApp checks the return value of validate
The original error causing failed validation is still swallowed and not logged, which should probably be addressed at some point as well, but at least now values are correct.
This came up when …
> ExtensionPoint: return True on successful validate()

- jupyter_server/extension/manager.py
- jupyter_server/tests/extension/test_manager.py
- use traitlets for defaults, loading config_managers
- load default config manager with default config path by default
- remove semi-private attributes transparently exposed with public getters
in favor of making them public.
This way a fully default `ExtensionManager()` will find all extensions by default, without needing to instantiate a config manager first.
> ExtensionManager: load default config manager by default

- jupyter_server/extension/manager.py
This is helpful when developing and debugging extensions
> Include backtrace in debug output when extension fails to load

- CHANGELOG.md
Automated Changelog Entry for 1.7.0a1 on master
Python version: 1.7.0a1
After merging this PR run the "Draft Release" Workflow with the following inputs
| Version Spec | 1.7.0a1 |
> Automated Changelog Entry for 1.7.0a1 on master

- setup.cfg
This bumps the minimum core dependency to `4.6.0` since that version of core is the first to include the `is_hidden()` method - on which the server relies.  These dependencies had been inherited from Notebook and it defines `is_hidden()` locally so the previous core dependency (`4.4.0`) is still valid in that scenario.
Fixes #496
> Increase minimum jupyter_core dependency

- CHANGELOG.md
Automated Changelog Entry for 1.7.0a2 on master
Python version: 1.7.0a2
After merging this PR run the "Draft Release" Workflow with the following inputs
| Version Spec | 1.7.0a2 |
> Automated Changelog Entry for 1.7.0a2 on master

- jupyter_server/services/nbconvert/handlers.py
> Make nbconvert root handler asynchronous

- jupyter_server/services/kernels/kernelmanager.py
Closes https://github.com/jupyter-server/jupyter_server/issues/403. This change aligns the implementation of `MappingKernelManager.start_kernel` with its docstring. 
It is worth mentioning that in the [API Doc](https://jupyter-server.readthedocs.io/en/latest/developers/rest-api.html?highlight=post#post--api-kernels), there is currently no method for starting a kernel by specifying a `kernel_id`. As such, no changes are made to `jupyter_server/tests/services/kernels/test_api.py`. Nevertheless, this change provides a _possibility_ to support such functionality if that is required in future.
> Use kernel_id for new kernel if it doesn't exist in MappingKernelManager.start_kernel

- setup.cfg
This dependency should have been dropped as part of the work for #382.
Resolves #281
> Drop dependency on pywin32

- jupyter_server/_version.py
- pyproject.toml
- setup.cfg
Packaging should be a build time dependency only.
> Remove Packaging Dependency

- CHANGELOG.md
Automated Changelog Entry for 1.7.0 on master
Python version: 1.7.0
After merging this PR run the "Draft Release" Workflow with the following inputs
| Version Spec | 1.7.0 |
> Automated Changelog Entry for 1.7.0 on master

- jupyter_server/serverapp.py
init_httpserver references IOLoop.current()
If a server extension sets an asyncio EventLoopPolicy, any prior reference to IOLoop.current or asyncio.get_event_loop() will be invalidated.
We should try to avoid this during intialize at all, or at least until the very end.
Arguably, the http server listen should occur in `.start()`
There is one other reference to the loop in terminado: https://github.com/jupyter/terminado/pull/102
> init_httpserver at the end of initialize

- jupyter_server/pytest_plugin.py
- jupyter_server/serverapp.py
tornado should still work better with Selector, even though 6.1 isn't *broken* with proactor. Picking Selector avoids the extra thread, which runs a Selector anyway.
So the choice is really between:
- Proactor in main thread for coroutines, but ~all IO in a Selector in another thread
- one Selector loop for everything
cf https://github.com/jupyter/notebook/pull/6052
> restore preference for SelectorEventLoop on Windows

- jupyter_server/services/config/manager.py
`default` is not a kwarg of the traitlet constructor (default_value is)
The result was a warning on every jupyter server startup that tag metadata was being stored, but this is deprecated. The default value was *not* being set.
> set default config dir name

- jupyter_server/tests/extension/test_manager.py
- jupyter_server/tests/test_terminal.py
Windows Terminal tests were disabled in jupyter-server/jupyter_server#201, but can now be enabled based on improvements in `pywinpty` 1.1. Also fixes test failure introduced in jupyter-server/jupyter_server#504
> Enable Server Tests on Windows

- jupyter_server/services/contents/filecheckpoints.py
- jupyter_server/services/contents/fileio.py
- jupyter_server/services/contents/filemanager.py
- jupyter_server/services/contents/largefilemanager.py
- jupyter_server/services/nbconvert/handlers.py
- setup.cfg
Upgrade anyio to 3.1 for all supported python versions. 
Fixes #505
> Upgrade anyio to 3.1 for all py versions

- jupyter_server/extension/manager.py
This provides a single, public property in the server extension API to return a deterministic list of server extensions.
This doesn't change much in server. We were already sorting extensions alphabetically by their keys. This change allows nbclassic to monkey-patch this property (as a special case) and provide a list of server extensions with nbclassic *always* first and the rest sorted alphabetically. See jupyterlab/nbclassic#56 for more details.
> Expose a public property to sort extensions deterministically.

- CHANGELOG.md
Automated Changelog Entry for 1.8.0 on master
Python version: 1.8.0
| Version Spec | 1.8.0 |
> Automated Changelog Entry for 1.8.0 on master

- .github/workflows/downstream.yml
Ensure that local changes are compatible with prerelease versions of downstream packages
Similar to the workflow used in [`traitlets`](https://github.com/ipython/traitlets/blob/main/.github/workflows/downstream.yml).
> Test Downstream Packages

- .gitignore
- jupyter_server/gateway/gateway_client.py
This lets you configure the "\<type\>" string that gets added (along with a space) to the front of the auth token in the header of all HTTP requests made to a gateway.
Technically, the current default (`"token"`) is invalid with respect to the authorization header spec, but I kept it for backwards compatibility: https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#authentication_schemes
> adds `GatewayClient.auth_scheme` configurable

- README.md
Old link was still pointing to issue in this repo but it was transferred to https://github.com/jupyter-server/team-compass/issues/1 and then replaced by new issue for 2020. Should both links be included, or just the current one?
> Update link to meeting notes

- jupyter_server/services/contents/manager.py
There is a bug in AsyncContentsManager#exists.
```
async def exists(self, path):
return await (ensure_async(self.file_exists(path)) or ensure_async(self.dir_exists(path)))
```
it always returns `False` when `file_exists` returns `False`
reproduce code:
```
from jupyter_server.utils import ensure_async
import asyncio
async def dir_exists():
return True
async def file_exists():
return False
async def exists():
return await (ensure_async(file_exists()) or ensure_async(dir_exists()))
if __name__ == '__main__':
a = asyncio.get_event_loop().run_until_complete(exists())
print(a)
```
> Fixes AsyncContentsManager#exists

- jupyter_server/services/nbconvert/handlers.py
It looks like the call to [nbconvert's `get_exporter` function](https://github.com/jupyter/nbconvert/blob/90b3911ed9b155e8ca3680ca4581d9344aa10be0/nbconvert/exporters/base.py#L92-L129) is not thread-safe:
https://github.com/jupyter-server/jupyter_server/blob/450010eae202ccc6d7a92515629c1c765068451e/jupyter_server/services/nbconvert/handlers.py#L23
And I can see that JupyterLab makes multiple concurrent requests to `/api/nbconvert`. This PR works around that issue using a lock.
Fixes https://github.com/jupyterlab/jupyterlab/issues/10442
> Fix nbconvert handler

- CHANGELOG.md
Automated Changelog Entry for 1.9.0 on master
Python version: 1.9.0
| Version Spec | 1.9.0 |
> Automated Changelog Entry for 1.9.0 on master

- package-lock.json
Bootstrap was fetched from `localhost:5559` in the lock file, instead of from the official npm registry
> Rebuild package-lock, fixing local setup

- jupyter_server/extension/application.py
- jupyter_server/tests/namespace-package-test/README.md
- jupyter_server/tests/namespace-package-test/setup.cfg
- jupyter_server/tests/test_utils.py
- jupyter_server/utils.py
This allows Jupyter extensions to be developed in [Python namespace packages](https://packaging.python.org/guides/packaging-namespace-packages/).
Related to: https://github.com/jupyter-server/jupyter_server/issues/222#issuecomment-624774795
See [PEP420](https://www.python.org/dev/peps/pep-0420/#id24).
Currently Jupyter Server extensions developed in Python namespace packages fall over with some nasty traceback:
```console
$ t_ns_jps_ext
[I 2021-05-19 12:40:39.457 ServerApp] t_namespace | extension was successfully linked.
File ".../t_ns_jps_ext", line 33, in <module>
sys.exit(load_entry_point('jps-namespace-extension', 'console_scripts', 't_ns_jps_ext')())
File ".../python3.9/site-packages/jupyter_server/extension/application.py", line 518, in …
```
> extensions: allow extensions in namespace packages

- jupyter_server/serverapp.py
- jupyter_server/tests/test_serverapp.py
Fixes https://github.com/jupyter-server/jupyter_server/issues/534
- Add a new trait to represent the "preferred" or "starting" directory (e.g., preferred_dir)
- preferred_dir
- will default to root_dir (aka notebook_dir)
- is required to be an existing directory residing at or within root_dir
- is a "suggestion" to client applications. Client applications can honor preferred_dir and start their file-browser at preferred_dir instead of root_dir.
- If root_dir is updated and preferred dir is no longer a subdir or equal to root_dir, then it will be updated to use the root_dir and emit a warning.
> PR: Add a new preferred-dir traitlet

- docs/source/developers/extensions.rst
- jupyter_server/extension/application.py
- jupyter_server/extension/manager.py
- jupyter_server/pytest_plugin.py
- jupyter_server/serverapp.py
- jupyter_server/tests/extension/test_app.py
- jupyter_server/utils.py
closes https://github.com/jupyter-server/jupyter_server/issues/241
Call a `stop_extension` method for each extension app on server shutdown if present.
Not sure how to go about testing this, any examples for the other `cleanup_*` methods?
> stop hook for extensions

- .github/workflows/downstream.yml
- .github/workflows/integration-tests.yml
- .github/workflows/python-linux.yml
- .github/workflows/python-macos.yml
- .github/workflows/python-windows.yml
- CONTRIBUTING.rst
- README.md
- conftest.py
- examples/simple/tests/conftest.py
- jupyter_server/auth/security.py
- jupyter_server/traittypes.py
- pyproject.toml
- setup.cfg
Some small test changes:
* Use the hash of the `setup.py` file for pip caching  (rather than `setup.py`)  in all actions.
One action is already using the `setup.cfg` file:
https://github.com/jupyter-server/jupyter_server/blob/51e3ec362b2b12af48f0e101959c4cbec9d5cb33/.github/workflows/check-release.yml#L27
The others aren't:
https://github.com/jupyter-server/jupyter_server/blob/51e3ec362b2b12af48f0e101959c4cbec9d5cb33/.github/workflows/python-linux.yml#L34
The pip environment may have been frozen for a little while because of this?
* Define `pytest_plugins` in a top-level conftest file to support pytest 4+.
* Pin pytest>=6 as earlier versions ignored the configuration in the `pytest.toml` file.
* Run doctests in pytest (0.34% coverage increase :laughing:).
* Test against Python 3.10-dev …
> small test changes

- CONTRIBUTING.rst
`pytest examples/simple` gives the following error:
```
==================================================================== test session starts =====================================================================
platform linux -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/david/github/davidbrochart/jupyter_server/examples/simple, configfile: pytest.ini
plugins: tornasync-0.6.0.post2, console-scripts-1.2.0, anyio-3.2.1, cov-2.12.1, mock-3.6.1
collected 2 items                                                                                                                                            
examples/simple/tests/test_handlers.py EE                                                                                                              [100%] …
```
> Fix examples/simple test execution

- CHANGELOG.md
Automated Changelog Entry for 1.10.0 on master
Python version: 1.10.0
| Version Spec | 1.10.0 |
> Automated Changelog Entry for 1.10.0 on master

- jupyter_server/tests/test_utils.py
- jupyter_server/utils.py
> Protect against unset spec

- CHANGELOG.md
Automated Changelog Entry for 1.10.1 on master
Python version: 1.10.1
| Version Spec | 1.10.1 |
> Automated Changelog Entry for 1.10.1 on master

- docs/source/other/full-config.rst
- jupyter_server/serverapp.py
I spotted a typo in the help output for `allow_password_change`
> Fix typo in allow_password_change help

- jupyter_server/serverapp.py
Ensure the needed space is present between `community`and `resources` to fix the following welcome message.
` in contributing to the platform, please visit the communityresources section at https://jupyter.org/community.html``
> Add the needed space in the welcome message

- jupyter_server/extension/application.py
This was broken by an unintentionally removed line in 0d11ffca.
Fixes #550
> fix: make command line aliases work again

- jupyter_server/auth/login.py
The get_secure_cookie interface returns bytes not str.
https://www.tornadoweb.org/en/stable/web.html#tornado.web.RequestHandler.get_secure_cookie
This fixes a minor issue where `handler.get_current_user` would return bytes rather than str.
Log the result of `handler.get_current_user()`, minimal example:
```python
class MyExtensionHandler(ExtensionHandlerMixin, JupyterHandler):  
@tornado.web.authenticated
def get(self):
user = self.get_current_user()
self.log.info(user)                                                 
self.write('hello world')  
```
Remove the token from the URL and reload the page (forces server to load the cookie value).
You should see the same token (because it was cashed in the cookie) but as bytes:
```
[I 2021-07-28 16:21:32.922 MyExtensionApp] …
```
> decode bytes from secure cookie

- CHANGELOG.md
Automated Changelog Entry for 1.10.2 on master
Python version: 1.10.2
| Version Spec | 1.10.2 |
> Automated Changelog Entry for 1.10.2 on master

- .github/workflows/check-release.yml
- pyproject.toml
Move link checking to a separate job and use new `check-links` action from `jupyter_releaser`.
> Clean up link checking

- jupyter_server/transutils.py
Without stacklevel=2, the warnings are a bit useless as we don't know
where the deprecated function is used.
> Set stacklevel on warning to point to the right place.

- jupyter_server/services/contents/filemanager.py
- jupyter_server/tests/services/contents/test_manager.py
> Allow non-empty directory deletion through settings

- .github/workflows/python-macos.yml
- jupyter_server/extension/manager.py
- jupyter_server/serverapp.py
- jupyter_server/tests/extension/test_app.py
- jupyter_server/tests/extension/test_manager.py
- jupyter_server/tests/services/kernels/test_cull.py
- jupyter_server/tests/test_terminal.py
We have this nice setting for having extension load failure raise errors instead of silently failing. We should respect it 😄
> Respect reraise setting

- jupyter_server/pytest_plugin.py
Fixes a small error in the `jp_ws_fetch` fixture where the `headers` provided to `client_fetch` were ignored in requests.
> pytest_plugin: allow user specified headers in jp_ws_fetch

- jupyter_server/base/handlers.py
- jupyter_server/services/shutdown.py
> Shutdown kernels/terminals on api/shutdown

- jupyter_server/base/zmqhandlers.py
- jupyter_server/services/contents/handlers.py
- jupyter_server/services/kernels/handlers.py
- jupyter_server/services/sessions/handlers.py
Fix the jupyter_client warning:
```
/home/martin/miniconda3/envs/xeus-python/lib/python3.9/json/encoder.py:257: 
UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
```
> Fix jupyter_client warning

- CHANGELOG.md
Automated Changelog Entry for 1.11.0 on master
Python version: 1.11.0
| Version Spec | 1.11.0 |
| Since | v1.10.2 |
> Automated Changelog Entry for 1.11.0 on master

- jupyter_server/services/kernels/handlers.py
I had the following error locally:
```
[Voila] Kernel shutdown: c7f832d5-6b46-4f77-9f98-f0b9ca6e7ac8
[Voila] WARNING | Timeout waiting for kernel_info reply from c7f832d5-6b46-4f77-9f98-f0b9ca6e7ac8
[Voila] ERROR | Error opening stream: HTTP 404: Not Found (Kernel does not exist: c7f832d5-6b46-4f77-9f98-f0b9ca6e7ac8)
```
This was because I closed the Voila application before the client could
finish connecting to the kernel.
With this PR, it should shutdown the kernel properly and be silent after
not being able to connect.
> Do not log connection error if the kernel is already shutdown

- jupyter_server/serverapp.py
The default value for this `min_open_files_limit` is `None` on Windows, but this trait doesn't (currently) allow `None`. This was causing issues in nbclassic unit tests, https://github.com/jupyterlab/nbclassic/pull/63
> [BUG]: allow None for min_open_files_limit trait

- CHANGELOG.md
Automated Changelog Entry for 1.11.1 on master
Python version: 1.11.1
| Version Spec | 1.11.1 |
| Since | v1.11.0 |
> Automated Changelog Entry for 1.11.1 on master

- jupyter_server/pytest_plugin.py
- jupyter_server/tests/services/kernels/test_api.py
- jupyter_server/tests/services/kernels/test_cull.py
- jupyter_server/tests/services/sessions/test_api.py
- jupyter_server/tests/test_terminal.py
> add a pytest fixture for capturing logging stream

- jupyter_server/tests/services/nbconvert/test_api.py
Relaxes one of the NBConvert API tests, so it's not dependent on NBConvert versions and only tests the REST API.
> Avoid dependency on NBConvert versions for REST API test

- setup.cfg
Unix socket support was ported from Notebook which has a test that uses `requests-unixsocket` to test the functionality.  Later, we updated the Notebook test to use a lazy import so we could [remove this dependency on Windows](https://github.com/jupyter/notebook/pull/5650).
The tests within jupyter_server are quite different and it appears, based on the successful tests, that this dependency isn't required at all.  I'm sure it was just an artifact from the original port.  This pull request removes the dependency.
Fixes: #598
> Remove requests-unixsocket dependency

- jupyter_server/auth/login.py
> Fix \s deprecation warning

- CHANGELOG.md
Automated Changelog Entry for 1.11.2 on master
```
Python version: 1.11.2
```
| Version Spec | 1.11.2 |
| Since | v1.11.1 |
> Automated Changelog Entry for 1.11.2 on master

- jupyter_server/auth/login.py
- jupyter_server/base/handlers.py
- jupyter_server/base/zmqhandlers.py
This PR fixes a bug with the `allow_origin_pat` which prevented the Jupyter server from recognizing and parsing regex patterns.  Follows from discussions with @mariobuikhuizen on https://github.com/mariobuikhuizen/voila-embed/issues/24.  Example traceback of the current broken implementation that this PR fixes is 
```
File "/Users/bcherinka/anaconda3/envs/havokve/lib/python3.8/site-packages/tornado/http1connection.py", line 273, in _read_message
delegate.finish()
File "/Users/bcherinka/anaconda3/envs/havokve/lib/python3.8/site-packages/tornado/routing.py", line 268, in finish
self.delegate.finish()
File "/Users/bcherinka/anaconda3/envs/havokve/lib/python3.8/site-packages/tornado/web.py", line 2290, in finish
self.execute()
File …
```
> Fix allow_origin_pat property to properly parse regex

- jupyter_server/serverapp.py
- jupyter_server/services/kernels/handlers.py
This closes #605 
Two methods in the class `ZMQChannelsHandler` were using the `logging` function directly instead of `self.log` method to emit logs. We already have a [default format](https://github.com/jupyter-server/jupyter_server/blob/90f619cf11eec842a27eec25692f9d65adccf169/jupyter_server/extension/application.py#L212) set for all Jupyter server logs, so this PR updates the following methods' logging calls to keep the format consistent. 
- `on_kernel_restarted`
- `on_restart_failed`
- Replace all logs emitted with direct use of `logging` with the instantiated class's own logging method: `self.log`.
- Add optional `log` parameter to `list_running_servers` to add missing warning log for failed server info file deletion.
While trying to reproduce the logs with `logging`, I found out …
> Consistent logging method

- jupyter_server/serverapp.py
avoids collisions across a given host
closes https://github.com/jupyterhub/jupyterhub/issues/3624
> set xsrf cookie on base url

- jupyter_server/tests/services/contents/test_api.py
test_list_notebooks was failing on file systems with unicode
normalization different from the encoding used in the strings. In particular on macOS with HFS+ I got failures for four of the file names. This is because HFS+ uses normalization form D while normalization form C is more commonly used, especially on Linux.
By normalizing the name and path read from disk to NFC we avoid the mismatch as long as no NFD strings are added to the `dirs` tuples. There are other unicode normal forms and normalization is not necessarily invertible so this is not a perfect solution.
I can think of two alternative solutions:
1. Refrain from using any unicode symbols that have different representations in the various normal forms.
2. Write temporary files to disk somewhere, the read back the paths and …
> test_api: Normalize file name and path

- jupyter_server/base/zmqhandlers.py
- jupyter_server/pytest_plugin.py
- jupyter_server/services/kernels/handlers.py
- jupyter_server/services/kernels/kernelmanager.py
- jupyter_server/services/sessions/handlers.py
- jupyter_server/tests/services/kernels/test_api.py
- jupyter_server/tests/services/kernels/test_cull.py
- jupyter_server/tests/services/kernelspecs/test_api.py
- jupyter_server/tests/services/sessions/test_api.py
Fixes https://github.com/jupyter-server/jupyter_server/issues/592.
Fixes https://github.com/jupyterlab/jupyterlab/issues/11338
Requires https://github.com/jupyter/jupyter_client/pull/712 in order to use the new feature.
We cannot make `use_pending_kernels` default to `True` before a major version bump because clients like JupyterLab are expecting kernel process startup errors to be given as part of the response to a POST on `/api/sessions`.  
This PR needs an alternate way of surfacing that error as discussed in #592.
There is also a behavior change of a restart being ignored (and erroring) if the process has not yet started.
- Set the `execution_state` to `"dead"` and set the `"reason"` based on the startup error
- Add handling of the `"reason"` field to the kernel response model
- Make …
> Use pending kernels

- CHANGELOG.md
Automated Changelog Entry for 1.12.0 on master
```
Python version: 1.12.0
```
| Version Spec | 1.12.0 |
| Since | v1.11.2 |
> Automated Changelog Entry for 1.12.0 on master

- .github/workflows/check-release.yml
- .github/workflows/integration-tests.yml
- .github/workflows/python-linux.yml
- .github/workflows/python-macos.yml
- .github/workflows/python-windows.yml
Use the [`base_setup`](https://github.com/jupyterlab/maintainer-tools#base-setup) action available from `maintainer-tools` to consolidate workflows.
> Use maintainer-tools base setup action

- jupyter_server/services/kernels/kernelmanager.py
This is the result of investigating the failing `js-services` tests in JupyterLab: https://github.com/jupyterlab/jupyterlab/issues/11548
Looking at the code, it looks like this future is ensured with `asyncio.ensure_future` but never awaited.
> await _finish_kernel_start

- .github/workflows/integration-tests.yml
- .github/workflows/python-linux.yml
- .github/workflows/python-macos.yml
Spotted while looking at the content of the workflows.
Normally it should be fine to switch to `3.10` final now.
> Update to Python 3.10 in the CI workflows

- CHANGELOG.md
Automated Changelog Entry for 1.12.1 on master
```
Python version: 1.12.1
```
| Version Spec | 1.12.1 |
| Since | v1.12.0 |
> Automated Changelog Entry for 1.12.1 on master

- jupyter_server/services/kernels/handlers.py
Fixes #622.
Notice that we do not need to wait for this [JEP]( https://github.com/jupyter/enhancement-proposals/pull/82) to be accepted before merging this PR, since the current specification of the protocol does not prevent to send `kernel_info` requests on the control channel.
> Nudge on the control channel instead of the shell

- .github/workflows/downstream.yml
Use the new downstream test action from `maintainer-tools`.
> Clean up downstream tests

- jupyter_server/services/sessions/sessionmanager.py
- jupyter_server/tests/services/sessions/test_manager.py
Fixes #611
Makes the session database path a configurable trait and avoids overwriting the database if it exists.
Also, sets the database's isolation level to `None` so that it autocommits all changes after every change.
> Persistent session storage

- CHANGELOG.md
Automated Changelog Entry for 1.13.0 on master
```
Python version: 1.13.0
```
| Version Spec | 1.13.0 |
| Since | v1.12.1 |
> Automated Changelog Entry for 1.13.0 on master

- .github/workflows/python-macos.yml
Hopefully fix recent errors seen on the macos pypy [check](https://github.com/jupyter-server/jupyter_server/runs/4436974425?check_suite_focus=true).  cf https://foss.heptapod.net/pypy/pypy/-/issues/3314
> Fix macos pypy check

- jupyter_server/services/kernels/handlers.py
Fixes #633, which broke many kernels in Jupyter Server 1.13.0.
This nudges _both_ the control and shell channels, for now. At some point in the future, once we've updated enough kernels, we can drop the shell info request.
> nudge both the shell and control channels

- CHANGELOG.md
Automated Changelog Entry for 0.13.1 on master
```
Python version: 0.13.1
```
| Version Spec | 0.13.1 |
| Since | v1.13.0 |
> Automated Changelog Entry for 0.13.1 on master

- .pre-commit-config.yaml
- docs/source/conf.py
- examples/simple/conftest.py
- jupyter_server/__init__.py
- jupyter_server/auth/__init__.py
- jupyter_server/prometheus/metrics.py
- jupyter_server/serverapp.py
- jupyter_server/services/config/__init__.py
- jupyter_server/utils.py
- setup.cfg
significant time savings in pre-commit
pylint was only checking for one issue, which flake8 supports, but skipped in config
remove the skip in flake8 config, so pylint can be removed
> remove redundant pylint check

- jupyter_server/services/sessions/sessionmanager.py
- jupyter_server/tests/services/sessions/test_manager.py
- package-lock.json
Port of https://github.com/jupyter/notebook/pull/6245
https://github.com/jupyter-server/jupyter_server/issues/110
> handle KeyError when get session

- jupyter_server/services/contents/filemanager.py
- jupyter_server/services/contents/largefilemanager.py
The `pre_save_hook` can potentially change the model, so checking for the `type` and `content` should be done after the call to the hook.
This will be needed in JupyterLab when we save documents from the back-end. In this case, the content won't be sent through the HTTP endpoint, but the hook will populate the model's content from the RTC server.
See https://github.com/jupyterlab/jupyterlab/pull/11599.
> Run pre_save_hook before model check

- jupyter_server/serverapp.py
This pull request addresses the display of IPv6 URLs:
* Just like `0.0.0.0`, `::` is replaced with the hostname.
* Literal IPv6 addresses are enclosed in square brackets, e.g. `::1` is turned into `[::1]`, to separate the address from the port number.
> Print IPv6 url as hostname or enclosed in brackets

- jupyter_server/tests/services/kernels/test_api.py
This is response to https://github.com/jupyter/jupyter_client/pull/732.
https://github.com/jupyter/jupyter_client/pull/732 expands the initial pending kernels work in https://github.com/jupyter-server/jupyter_server/pull/593 and makes "shutdown", "interrupt", and "restart" show as pending states.
Jupyter server's unit tests should await these various states when using pending kernels. Here, I've added the needed await statements and made it backwards compatible with old versions of jupyter client (before pending kernels were introduced).
> Add more awaits for pending kernel in unit tests

- CHANGELOG.md
Automated Changelog Entry for 1.13.2 on main
```
Python version: 1.13.2
```
| Version Spec | 1.13.2 |
| Since | v1.13.1 |
> Automated Changelog Entry for 1.13.2 on main

- jupyter_server/tests/services/sessions/test_api.py
This is a follow-up PR to #654. The session unit tests also need to changes for the [work landing in Jupyter Client around pending kernels.](https://github.com/jupyter/jupyter_client/pull/732)
> More updates to unit tests for pending kernels work

- setup.cfg
Fixes #661. 
We previously had a shim for the `'traitlets.utils.descriptions.describe` function for backwards compatibility with traitlets 4.3.x. We dropped this shim in #650 while dropping Python 3.6 support.
I don't think we need to add this shim back. Since traitlets 5.x has been released for over a year, I think we can bump its dependency.
> bump traitlets dependency

- CHANGELOG.md
Automated Changelog Entry for 1.13.3 on main
```
Python version: 1.13.3
```
| Version Spec | 1.13.3 |
| Since | v1.13.2 |
> Automated Changelog Entry for 1.13.3 on main

- jupyter_server/nbconvert/handlers.py
Fixes https://github.com/jupyterlab/jupyterlab/issues/11885
Fixes https://github.com/jupyterlab/jupyterlab/issues/11877
> Fix nbconvert handler run_sync()

- CHANGELOG.md
Automated Changelog Entry for 1.13.4 on main
```
Python version: 1.13.4
```
| Version Spec | 1.13.4 |
| Since | v1.13.3 |
> Automated Changelog Entry for 1.13.4 on main

- jupyter_server/tests/services/kernels/test_api.py
- jupyter_server/tests/services/kernels/test_cull.py
- jupyter_server/tests/services/sessions/test_api.py
Unit tests that test pending kernels are failing on our Windows CI.
It will take me some time to investigate these failures, so I proposed temporarily skipping these tests in #672. We will keep that issue open to track updates in the future.
I've also changed the pytest logic a bit to be more explicit when testing `MappingKernelManager` vs. `AsyncMappingKernelManager` and `use_pending_kernels`.
> (temporarily) skip pending kernels unit tests on Windows CI

- .github/workflows/trigger_precommit.yml
Experimental support for running `pre-commit` on a [PR](https://github.com/jupyterlab/maintainer-tools#pr-script-1).
With this configuration, any member, owner, or collaborator can comment `auto run pre-commit`, and it will run `pre-commit` against the PR and push the change.
For now, we use the `GITHUB_TOKEN` provided to the workflow.
The result is that the workflows are not automatically re-run for the commit: we have to close and re-open the PR.
We can later decide to use an access token from `@jupyterlab-bot`, which would re-run the workflows.
The end state is that we will ideally use [jupyterlab-probot](https://github.com/jupyterlab/jupyterlab-probot/issues/14) for this feature once it is available there.
This gives us a chance to kick the tires on the concept with minimal risk.
> Add Auto Pre-Commit

- .github/workflows/python-linux.yml
- pyproject.toml
> Clean up full install test

- jupyter_server/base/zmqhandlers.py
- jupyter_server/serverapp.py
- jupyter_server/services/kernels/handlers.py
Jupyter web clients (e.g. Jupyter Lab) communicate with Jupyter kernels over websockets, but kernels natively use Zero-MQ sockets as their transport layer. The Jupyter server acts as a bridge between kernels and web clients, and is responsible for forwarding messages to/from kernels over Zero-MQ sockets from/to web clients over websocket:
```
kernel <-----> Jupyter server <-----> web client
^                      ^
|                      |
Zero-MQ sockets           websocket
```
The kernel wire protocol over Zero-MQ sockets is well specified. It takes advantage of multipart messages, allowing to decompose a message into parts and to send and receive them unmerged. The following table shows the message format (the beginning has been omitted for clarity):
| ... | 0 | 1 | 2 | 3 | 4 | 5 | ... …
> Protocol alignment

- CHANGELOG.md
Automated Changelog Entry for 1.13.5 on main
```
Python version: 1.13.5
```
| Version Spec | 1.13.5 |
| Since | v1.13.4 |
> Automated Changelog Entry for 1.13.5 on main

- .github/workflows/integration-tests.yml
- .github/workflows/python-linux.yml
- .github/workflows/python-macos.yml
- .github/workflows/python-windows.yml
This should make it a bit easier to debug CI failures.
> Use pytest-github-actions-annotate-failures

- .github/workflows/python-linux.yml
> Add Minimum Requirements Test

- .github/workflows/python-linux.yml
- pyproject.toml
- setup.cfg
> Clean up Dependency Handling

- jupyter_server/extension/application.py
- jupyter_server/serverapp.py
Rather than duplicating its logic, re-use the value. JupyterHub overrides this in the base ServerApp (https://github.com/jupyterhub/jupyterhub/issues/3804), but the overridden value should be used for both:
1. locating extensions,
2. when extensions look for their own config files
> Re-use ServerApp.config_file_paths for consistency

- jupyter_server/services/contents/filemanager.py
- jupyter_server/services/contents/largefilemanager.py
See https://github.com/jupyter-server/jupyter_server/pull/696#discussion_r823820427.
cc @kevin-bates
> Call pre_save_hook only on first chunk of large files

- jupyter_server/services/contents/filemanager.py
The `AsyncFileContentsManager` was missing `async` definitions of the a few required methods. Therefore because of the multiple inheritance, the `FileContentsManager` definitions were being used resulting in an unpleasant developer experience when implementing a proxy Contents Manager responsible for delegating to an `AsyncContentsManager` (for our remote storage system at Twitter) or an `AsyncLargeFileManager`.  This feels like undesired behavior to have a few CM methods need to be execute in a synchronous style and some in an async style using `await` requiring additional boilerplate type checking in my case.
> Implement Required Methods in Async Manner

- jupyter_server/services/kernels/kernelmanager.py
Avoid deserializing the entire message until we know it is a status message to avoid deserializing large iopub contents.
> Clean up activity recording

- docs/source/developers/savehooks.rst
- jupyter_server/services/contents/filemanager.py
- jupyter_server/services/contents/largefilemanager.py
- jupyter_server/services/contents/manager.py
- tests/test_files.py
> Register pre/post save hooks, call them sequentially

- CHANGELOG.md
Automated Changelog Entry for 1.15.0 on main
```
Python version: 1.15.0
```
| Version Spec | minor |
| Since | v1.13.5 |
> Automated Changelog Entry for 1.15.0 on main

- jupyter_server/extension/application.py
- jupyter_server/serverapp.py
This reverts commit 653740cbad7ce0c8a8752ce83e4d3c2c754b13cb.
Fixes #727
> Revert "Re-use ServerApp.config_file_paths for consistency (#715)"

- CHANGELOG.md
Automated Changelog Entry for 1.15.1 on main
```
Python version: 1.15.1
```
| Since | v1.15.0 |
> Automated Changelog Entry for 1.15.1 on main

- jupyter_server/extension/application.py
- jupyter_server/serverapp.py
- tests/extension/test_app.py
reverts #732 with fix for MultipleInstanceErrors
> Fix server-extension paths (3rd time's the charm)

- CHANGELOG.md
Automated Changelog Entry for 1.15.3 on main
```
Python version: 1.15.3
```
| Since | v1.15.2 |
> Automated Changelog Entry for 1.15.3 on main

- jupyter_server/auth/decorator.py
Follow up on https://github.com/jupyter-server/jupyter_server/pull/717
Fixes https://github.com/jupyter-server/jupyter_server/issues/737
> raise no-authorization warning once and allow disabled authorization

- jupyter_server/extension/application.py
Some extensions (e.g. JupyterLab) apparently may be loaded hooked up to a legacy NotebookApp, which is not a ServerApp.
Hopefully my last fix trying to finish  #730
Launching `jupyter notebook` with jupyterlab installed fails to load with:
```
traitlets.traitlets.TraitError: The 'serverapp' trait of a LabApp instance expected a ServerApp, not the NotebookApp at '0x1035b51c0'.
```
> Relax type checking on ExtensionApp.serverapp

- CHANGELOG.md
Automated Changelog Entry for 1.15.5 on main
```
Python version: 1.15.5
```
| Version Spec | 1.15.5 |
| Since | v1.15.4 |
> Automated Changelog Entry for 1.15.5 on main

- jupyter_server/auth/decorator.py
- jupyter_server/auth/utils.py
- jupyter_server/base/zmqhandlers.py
- jupyter_server/terminal/handlers.py
Looks like I missed one more place where a warning is needed when no authorizer is set.
Fixes #737 (hopefully completely).
> Missing warning when no authorizer in found ZMQ handlers

- CHANGELOG.md
Automated Changelog Entry for 1.15.6 on main
```
Python version: 1.15.6
```
| Version Spec | 1.15.6 |
| Since | v1.15.5 |
> Automated Changelog Entry for 1.15.6 on main

- jupyter_server/services/kernels/kernelmanager.py
This PR fixes an issue I'm seeing when working with pending kernels. 
There's race condition when shutting a kernel down. The entries in `_kernel_connections` and `_kernel_ports` for a pending shutdown get removed before that pending kernel fully finished terminating. 
This raises the following exception in the kernels handler as a consequence:
```
Uncaught exception GET /api/kernels/0b8f1e20-e8c6-43a2-bb96-8f07dc702636/channels?session_id=61f58256-f8d3-48f3-a12e-0ac6c0f4c856 (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/api/kernels/0b8f1e20-e8c6-43a2-bb96-8f07dc702636/channels?session_id=61f58256-f8d3-48f3-a12e-0ac6c0f4c856', version='HTTP/1.1', remote_ip='127.0.0.1')
File …
```
> wait to cleanup kernels after kernel is finished pending

- jupyter_server/services/contents/manager.py
- tests/services/contents/test_config.py
Try access the __name__ attribute on the function form of the hook, and
if it doesn't exist then use the string as the name.
Closes #753
> Handle importstring pre/post save hooks

- setup.cfg
Fix https://github.com/jupyter-server/jupyter_server/runs/5681044426?check_suite_focus=true where nbconvert 5.6.1 is used. But jinja2 3.1 was just release and drop some deprecated functions from v2. So requires at least nbconvert 6.2 that handle both jinja2 v2 and v3.
> Ensure minimal nbconvert support jinja2 v2 & v3

- jupyter_server/serverapp.py
- tests/test_serverapp.py
Addresses an unintentional regression in the calculation of the `connection_url` property of the `ServerApp` detailed in issue: #743
> Regression in connection URL calcuation in ServerApp

- CONTRIBUTING.rst
- pyproject.toml
- setup.cfg
- setup.py
Eventually we can use https://github.com/jupyter/jupyter-packaging/issues/138
> Install pre-commit automatically

- jupyter_server/kernelspecs/handlers.py
> Add `max-age` Cache-Control header to kernel logos

- jupyter_server/services/sessions/sessionmanager.py
- tests/services/sessions/test_manager.py
In the case where a (new) session has been created and a new kernel is launched, there can be time gap between when a kernel is actually started and its session is actually saved—specifically, if [`._finish_kernel_start()`](https://github.com/jupyter-server/jupyter_server/blob/cd1b1b886db08c6480329c3f0832d05f15d49a19/jupyter_server/services/kernels/kernelmanager.py#L219) takes any time at all. The same is true for deleting sessions; `shutdown_kernel` can take some time. I call this a "pending session".
I've been working on some tooling to synchronize sessions and kernels (more on that coming in a future PR). To achieve this, I need to be "aware" of pending sessions. Unfortunately, this isn't easily achievable without adding the plumbing directly to source code, hence this pull request. …
> add hook to observe pending sessions

- CHANGELOG.md
Automated Changelog Entry for 1.15.7 on main
```
Python version: 1.15.7
```
| Since | v1.15.6 |
> Automated Changelog Entry for 1.16.0 on main

- .github/workflows/enforce-label.yml
Take advantage of auto-labeling for dependabot and pre-commit-ci PRs from https://github.com/jupyterlab/maintainer-tools/pull/83/files.
> Give write permissions to enforce label workflow

- pyproject.toml
Take advantage of https://github.com/jupyter-server/jupyter_releaser/pull/287
This means that we don't have to set `post-version-spec` when releasing, it will bump to the next minor `.dev0` automatically.  When we run `next`, it will use the previous version from the changelog.  When we use `minor`, it will just drop the `.dev` suffix.
> Use new post-version-spec from jupyter_releaser

- docs/source/developers/savehooks.rst
> Update documentation about registering file save hooks

- jupyter_server/gateway/managers.py
Fixes https://github.com/jupyter-server/jupyter_server/issues/786
> Hydrate a Kernel Manager when calling GatewayKernelManager.start_kernel with a kernel_id

- docs/autogen_config.py
After this PR: https://github.com/jupyter-server/jupyter_server/pull/794, I noticed that full config doc is generated under this path: https://jupyter-server.readthedocs.io/en/latest/full-config.html, but it should be generated under https://jupyter-server.readthedocs.io/en/latest/other/full-config.html.
I guess, we missed `other/` in the destination path, since `autogen_config.py` is executed from  [`/docs/source`](https://github.com/jupyter-server/jupyter_server/tree/main/docs/source).
cc @Zsailer @blink1073
> Fix path for full config doc

- .github/workflows/integration-tests.yml
- .github/workflows/python-tests.yml
Makes it easier to maintain required checks for branch protection.
> Add helper jobs for branch protection

- CHANGELOG.md
Automated Changelog Entry for 1.16.1 on 1.x
```
Python version: 1.17.0
```
| Branch  | 1.x  |
| Version Spec | minor |
| Since | v1.16.0 |
> Automated Changelog Entry for 1.17.0 on 1.x

- jupyter_server/auth/decorator.py
- jupyter_server/auth/utils.py
- jupyter_server/base/handlers.py
- jupyter_server/base/zmqhandlers.py
- jupyter_server/terminal/handlers.py
warn once when populating the default, rather than requiring repeated warnings about its absence everywhere the authorizer might be used.
Left the warning as deprecated rather than removed, due to the fact that it's used in the now-forked jupyter_server_terminals
backported from #671
> (backport) ensure authorizer is defined

- docs/source/conf.py
- docs/source/operators/security.rst
- jupyter_server/auth/__init__.py
- jupyter_server/auth/authorizer.py
- jupyter_server/auth/decorator.py
- jupyter_server/auth/identity.py
- jupyter_server/auth/login.py
- jupyter_server/auth/utils.py
- jupyter_server/base/handlers.py
- jupyter_server/base/zmqhandlers.py
- jupyter_server/gateway/handlers.py
- jupyter_server/log.py
- jupyter_server/serverapp.py
- jupyter_server/services/api/api.yaml
- jupyter_server/services/api/handlers.py
- tests/auth/test_identity.py
- tests/auth/test_login.py
- tests/services/api/test_api.py
Draft implement of identity API (closes #638). Includes #165.
Key issues:
- Jupyter Server has never put any requirements on the return of `get_user` other than truthiness - this poses a challenge in coercing to a user model. I'm aware of two patterns:
1. current_user is a string username (the default), and
2. current_user is a dict with 'username' field or 'name' field (JupyterHub uses 'name')
so these are supported, and others result in `username: "unknown"`.
We could take this opportunity to _enforce_ a structure on .current_user, or we could require custom User objects to use a corresponding Authorizer class to define the new Authorizer.user_model method to adapt to the dict format.
- checking permissions - the design in #165 doesn't allow _a priori_ listing of available …
> Identity API at /api/me

- .github/workflows/python-tests.yml
- Fix pytest flag in `test_sdist`
- Test against `pypy-3.8` (`pypy-3.7` is still used in integration test job).
> CI cleanup

- CHANGELOG.md
Automated Changelog Entry for 2.0.0a0 on main
```
Python version: 2.0.0a0
```
| Version Spec | 2.0.0a0 |
| Since | v1.16.0 |
> Automated Changelog Entry for 2.0.0a0 on main

- .pre-commit-config.yaml
- pyproject.toml
this way, the formatters produce the same output whether run via pre-commit or not
> move isort, black config to pyproject.toml

- jupyter_server/auth/authorizer.py
- jupyter_server/base/handlers.py
- jupyter_server/serverapp.py
In many cases of custom implementations, these two will have some coupling. So it makes sense for the Authorizer to have access to the identity provider for shared info.
e.g. the HubAuth object, when working with JupyterHub.
> give authorizer handle on identity provider

- jupyter_server/base/handlers.py
related to async get_user in #671. Found during #825
> ensure user is defined in early short-circuit requests

- .github/workflows/python-tests.yml
Workaround for https://github.com/pypa/pip/issues/10222
> Do not use pre-releases for build dependencies

- jupyter_server/serverapp.py
When running `jupyter lab stop` the wrong endpoint was being called
> Call "/api/shutdown" instead of "/"

- jupyter_server/serverapp.py
If GatewayClient is enabled, it hardcodes the session_manager, kernel_manager, and kernelspec_manager. I think we still want these classes to be overridable. This PR keeps the defaults the same (backwards compatible) while also allowing it to be configurable.
> Enable GatewayClient managers to be configurable

- docs/source/conf.py
- pyproject.toml
Avoids pulling in runtime requirements when building with flit.
Fixes incorrect version in docs.
> Use static versions everywhere

- jupyter_server/gateway/managers.py
Because `GatewayKernelClient._channel_queues` is assigned at class scope only and not through self, this field is shared across `GatewayKernelClient` instances.
In case of 2 instances of `GatewayKernelClient`, the `_route_responses` will place messages in a shared queue, making it impossible to use multiple instances in parallel.
Simply assign the field in constructor.
Ran the tests locally and they passed.
> Fix GatewayKernelClient is consuming data from other kernel instances

- tests/services/events/mock_event.yaml
- tests/services/events/mockextension/mock_extension.py
- tests/services/events/mockextension/mock_extension_event.yaml
- tests/services/events/test_api.py
- tests/services/events/test_extension.py
Closes #852 
Chose to go with `jupyter.org` over `example.com` because `event.mock.jupyter.org/message` felt like it makes more sense.
Let me know if you guys think otherwise and I'll be happy to change.
> [Bug] Change test domain from `*.jupyter.com/*` to `*.jupyter.org/*`

- jupyter_server/services/sessions/sessionmanager.py
> Make start_kernel env extend os.environ

- .github/workflows/check-release.yml
- .github/workflows/python-tests.yml
- CONTRIBUTING.rst
- package-lock.json
- package.json
- pyproject.toml
- Uses new [hatch_jupyter_builder](https://github.com/blink1073/hatch_jupyter_builder) plugin
> Switch to hatch build plugin

- jupyter_server/gateway/managers.py
- tests/test_gateway.py
While working on the next Enterprise Gateway release, I ran into a couple of issues encountered when shutting down Jupyter Server when a Gateway is configured and there are outstanding kernel instances.
1.  The loop walking the set of outstanding kernels was being modified producing "RuntimeError: dictionary changed size during iteration". 
2. Attempts to delete a kernel known to Server but unknown to Gateway (due to culling or inadvertent termination on the gateway) was triggering an exception for the `404` when, for shutdown operations, this can be ignored.
This pull request addresses these issues and adds an appropriate test as well. (I confirmed expected test failures prior to applying the fixes.)
> Fix gateway kernel shutdown

- jupyter_server/extension/manager.py
import error may not be on the top-level module, it could deeper, e.g. during load another import fails, which is currently hidden
> Show import error when faiing to load an extension

- pyproject.toml
should get tests tests passing with tornado 6.2
tornado's following asyncio's lead in deprecating the concept of a 'current' event loop that's not running. This mostly affects our initialization/event-loop-starting code which is in `serverapp.py` and the test fixtures (largely in pytest-tornasync), since the event loop's running for everything else.
Rather than fully hiding the warnings, just avoid errors (I treated the equivalent asyncio warning the same). It's still useful info to know the warnings are being triggered.
We can use #876 to track avoiding these deprecations
> suppress tornado deprecation warnings

- jupyter_server/utils.py
This fixes an issue causing access to local files in Voila considered forbidden:
Accessing a file `./jupyter.svg` in Voila (`jupyter.svg` being under the root_dir) results in a:
```
File "/home/martin/micromamba/envs/voila/lib/python3.10/site-packages/mistune.py", line 661, in _process_link
return self.renderer.image(link, title, text)
File "/home/martin/github/voila/voila/exporter.py", line 34, in image
content = contents_manager.get(src, format='base64')
File "/home/martin/micromamba/envs/voila/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 386, in get
raise web.HTTPError(404, four_o_four)
tornado.web.HTTPError: HTTP 404: Not Found (file or directory does not exist: './jupyter.svg')
```
This was because the root_dir was set to …
> Normalize os_path

- CHANGELOG.md
Automated Changelog Entry for 1.18.0 on 1.x
```
Python version: 1.18.0
```
| Branch  | 1.x  |
| Version Spec | minor |
| Since | v1.17.1 |
> Automated Changelog Entry for 1.18.0 on 1.x

- jupyter_server/gateway/managers.py
- tests/test_gateway.py
ChannelQueue.get_msg is marked as async, however it's a blocking call.
Looking at https://github.com/jupyter/nbclient/blob/main/nbclient/client.py#L806, there is a call to `get_msg` which may block infinite. Now that code is fine, because the coroutine is being run as a background task and timeout being handled with asyncio.
However, thinking about a little bit, get_msg will block the entire thread, not giving a chance to other tasks to run.
We can easily make this method true async. I also considered asyncio.Queue, but that is not thread safe and we need it for recv_thread.
> Make ChannelQueue.get_msg true async

- jupyter_server/gateway/managers.py
- tests/test_gateway.py
In case the `response_router` encounters an error, the thread will exit and there is no code to check if it's still alive. This would mean waiting for messages that never arrives.
Added a simple flag based notification mechanism where the route_responses will notify channels that the thread is exiting.
Also because the route_responses thread depends on channels to be created, it is important to make sure we don't start this thread before starting channels.
> Notify ChannelQueue that the response router thread is finishing

- CHANGELOG.md
Automated Changelog Entry for 1.18.1 on 1.x
```
Python version: 1.18.1
```
| Branch  | 1.x  |
| Since | v1.18.0 |
> Automated Changelog Entry for 1.18.1 on 1.x

- CHANGELOG.md
Automated Changelog Entry for 2.0.1 on main
```
Python version: 2.0.1
```
| Since | v2.0.0a1 |
> Automated Changelog Entry for 2.0.1 on main

- .pre-commit-config.yaml
Fixes #905. Basically just prefer Node version available in system path instead of installing the latest stable version of Node upstream. Fixes pre-commit for some systems like AL2.
> default to system node version in precommit

- docs/source/operators/public-server.rst
> Fix owasp link

- jupyter_server/gateway/gateway_client.py
- tests/test_gateway.py
Re-add support removed in https://github.com/jupyter-server/jupyter_server/commit/573adc3de6de26f644afb27b5b7f037f63a1b45a
> Add back support for kernel launch timeout pad

- docs/source/operators/public-server.rst
Very small PR to fix code snippet syntax.
> Fix c.GatewayClient.url snippet syntax

- jupyter_server/services/sessions/sessionmanager.py
Manual backport of #679 and the cleanup PR #859.
> Backport  Inject session identifier into environment variable. #679 

- jupyter_server/base/handlers.py
- jupyter_server/extension/manager.py
- jupyter_server/services/kernels/kernelmanager.py
- tests/extension/test_app.py
This change finds a few places where `log.[somelevel](some_exc)`
was called and rewrites them to provide more information. Also updates
other logging statements in the same files to use logging best practices
(always put a static message in the first parameter, only substitute
variables in with `%` expressions).
> Improve logging of bare exceptions and other cleanups.

- CHANGELOG.md
Automated Changelog Entry for 2.0.0b0 on main
```
Python version: 2.0.0b0
```
| Version Spec | 2.0.0b0 |
| Since | v2.0.0a2 |
> Automated Changelog Entry for 2.0.0b0 on main

- jupyter_server/services/contents/handlers.py
In #884 we talked about the possibility to register new file types. It could be needed in the future, and maybe a `notebook` file type should be such a registered type (through a jupyter-server extension).
But for now an easier path would be to not throw an error when we get an unknown file type, and treat it as a generic `file`.
Closes https://github.com/jupyterlab/jupyterlab/pull/12719.
> Allow new file types

- jupyter_server/auth/identity.py
- jupyter_server/auth/utils.py
I created the PR starting from #825.
Adds the anonymous users logic used in JupyterLab. It stores the user info in the cookie to persist between sessions as was done with the user id.
> Adds anonymous users

- docs/source/operators/security.rst
[Previous section](https://github.com/jupyter-server/jupyter_server/blob/main/docs/source/operators/security.rst#authentication-and-authorization) has the following description
> The first step is "Authentication" (identifying who is making the request). This is handled by the [:class:`.IdentityProvider`](https://github.com/jupyter-server/jupyter_server/blob/main/docs/source/operators/security.rst#id7).
I think it's more correct to say `IdentityProvider` class is responsible for the "authentication" step, instead of "authorization"
> Fix typo in IdentityProvider documentation

- jupyter_server/services/nbconvert/handlers.py
asyncio.Lock references the current event loop, but there usually isn't one at import time. The result is that importing this handler always instantiates a current loop and attaches a lock to it, which may or may not be the loop that ultimately runs (app.io_loop).
Instead, create lock and attach it to the Handler class upon initializing the first handler of the class, which is always run inside the loop.
Also related to #876
> avoid creating asyncio.Lock at import time

- jupyter_server/services/contents/handlers.py
- tests/services/contents/test_api.py
Fixes #931 
This is a small refactor to avoid a 'NoneType' `AttributeError` when sending a POST request to `api/contents` that does not include a body. 
A body-less POST to the `api/contents/{path}` endpoint is also added to `services/contents/test_api.py:test_create_untitled`.
> Fix error that prevents posting to `api/contents` endpoint with no body

- jupyter_server/services/contents/handlers.py
As pointed out in [this comment](https://github.com/jupyter-server/jupyter_server/pull/937/files#r935733455), #937 introduced a bug in `api/contents` POST `copy_from` requests, leading to both `_copy` and a `_new_untitled` executing for an allowed copy. This PR fixes that bug by adding the `else` clause for the `copy_from` block.
Tested manually to ensure no `untitled` file is created on duplicate or copy/paste.
> Fix bug in `api/contents` requests for an allowed copy

- .pre-commit-config.yaml
The repo is incompatible with flake v5 and appears to be under-maintained.
> Fix flake8 v5 compat

- examples/simple/simple_ext1/handlers.py
- examples/simple/tests/test_handlers.py
- jupyter_server/pytest_plugin.py
- tests/auth/test_authorizer.py
Fixes https://github.com/jupyter-server/jupyter_server/issues/773
> Update pytest_plugin with fixtures to test auth in core and extensions

- CHANGELOG.md
Automated Changelog Entry for 2.0.0b1 on main
```
Python version: 2.0.0b1
```
| Version Spec | 2.0.0b1 |
| Since | v2.0.0b0 |
> Automated Changelog Entry for 2.0.0b1 on main

- jupyter_server/gateway/gateway_client.py
- jupyter_server/gateway/managers.py
GatewayKernelManager does not send the correct `Content-Type` header when issuing POST requests for kernel creation.
This was initially fixed in PR : #471 
But got reverted when gateway manager was refactored, in this commit : https://github.com/jupyter-server/jupyter_server/commit/062b5f42a8eed03da0d86e732d1b6718ed2ac471
> Correct content-type headers

- jupyter_server/gateway/gateway_client.py
- jupyter_server/gateway/managers.py
(cherry-picked from commit 15310fd)
> Backport PR #965: Correct content-type headers

- tests/services/events/mock_event.yaml
- tests/services/events/mockextension/mock_extension.py
- tests/services/events/mockextension/mock_extension_event.yaml
- tests/services/events/test_api.py
- tests/services/events/test_extension.py
Jupyter Events 0.5.0 enforces the `$id` field to be a URI. The unit tests here fail to meet this requirement. Updated the tests to handle this.
> fix issues with jupyter_events 0.5.0

- jupyter_server/serverapp.py
- tests/test_terminal.py
Fixes https://github.com/jupyterlab/jupyterlab/issues/12540. Allows configuring `terminado_settings` from command line with:
```
--ServerApp.terminado_settings="shell_command=['/bin/zsh']"
```
or if users are willing to accept the default tokenization by `shlex.split` with:
```
--ServerApp.terminado_settings="shell_command='/bin/zsh'"
```
Are there tests for configuration settings?
For context it is used in: [`jupyter_server_terminals`](https://github.com/jupyter-server/jupyter_server_terminals/blob/b8fea6404b8b5e5ee6ea8d69d3b680ee440e0508/jupyter_server_terminals/app.py#L44)
> Parse list value for `terminado_settings`

- jupyter_server/gateway/gateway_client.py
- tests/test_gateway.py
This PR adds an `accept_cookies` argument to `GatewayClient` class. Once enabled, `GatewayClient` accepts and manages cookie expiration when receiving cookies generated by load balancers serving notebook gateways. These cookies will be sent back in request headers for load balancers to decide which backend node to use.
Purposes and discussions in #967.
> Accept and manage cookies when requesting gateways

- CHANGELOG.md
Automated Changelog Entry for 2.0.0rc0 on main
```
Python version: 2.0.0rc0
```
| Draft Release | https://github.com/jupyter-server/jupyter_server/releases/tag/untagged-241bb129f48de8e1cbe0  |
| Since | v2.0.0b1 |
> Automated Changelog Entry for 2.0.0rc0 on main

- jupyter_server/gateway/gateway_client.py
- jupyter_server/gateway/managers.py
- tests/test_gateway.py
Today I learned that Lab includes the user's env in the `env` stanza of the kernel start request body.  I also learned that we were only filtering the server's env (i.e., the env of the jupyter server process) when applying the `env_whitelist` configurable to determine which envs to send to the gateway, then _unconditionally_ adding whatever was already in the start request's `env` stanza.  Instead, we need to be filtering _both_ the server's envs **and** the provided envs against the configured list.  This pull request makes this change.
Also, while we're at it, we should deprecate `env_whitelist` in favor of `allowed_envs` - similar to what was done with Kernelspec filtering in jupyter_client. This pull request makes that change as well.
> [Gateway] Fix and deprecate env whitelist handling

- .github/workflows/python-tests.yml
- pyproject.toml
Start testing the RC release of Python 3.11
> Test python 3.11 on ubuntu

- .github/workflows/integration-tests.yml
- .github/workflows/python-tests.yml
- jupyter_server/services/kernels/handlers.py
Testing against https://github.com/jupyter/jupyter_client/pull/835 (in the prerelease job and as an extra integration test run).
> Test with client 8 updates

- CHANGELOG.md
Automated Changelog Entry for 1.19.0 on 1.x
```
Python version: 1.19.0
```
| Draft Release | https://github.com/jupyter-server/jupyter_server/releases/tag/untagged-373efecd3418a14c320a  |
| Since | v1.18.1 |
> Automated Changelog Entry for 1.19.0 on 1.x

- .github/workflows/prep-release.yml
- .github/workflows/publish-release.yml
Experimental support for the simplified releaser workflow.  I added tag protection to this repository, meaning only those with "admin write" access can use the publish workflow.
> Add workflows for simplified publish

- docs/source/developers/extensions.rst
The current server extension disable instructions are incorrect, they are missing the keyword `extension`.
> Update server extension disable instructions

- CHANGELOG.md
Automated Changelog Entry for 1.19.1 on 1.x
```
Python version: 1.19.1
```
| Draft Release | https://github.com/jupyter-server/jupyter_server/releases/tag/untagged-b75f7701f8a765891a04  |
| Since | v1.19.0 |
> Automated Changelog Entry for 1.19.1 on 1.x

- .github/workflows/python-tests.yml
- jupyter_server/services/kernels/handlers.py
> Wrap the concurrent futures in an asyncio future

- RELEASE.md
While looking into adopting recent build framework changes in another repo, I ran into a couple of (minor) issues with the recently-added `hatchling` instructions.  I also took the liberty to update the variable `script_version` to `new_version` to have parity with its prompt (as well as `dev_version`).
> Fix some typos in release instructions

- .github/workflows/check-release.yml
- .github/workflows/python-tests.yml
- pyproject.toml
This updates us to use the version2 branch of releaser for check-release, and the check-links action from maintainer tools.  Once we release a v2 tag of releaser, we can update the workflows to target that tag.
> Update to version2 releaser

- .pre-commit-config.yaml
Use https://github.com/abravalheri/validate-pyproject to validate the pyproject.toml, including trove classifiers.
> Add pyproject validation

- .github/workflows/prep-release.yml
- .github/workflows/publish-release.yml
We need to rely on the user permissions check instead of using the user `GITHUB_TOKEN` directly, because even as an admin I was unable to push commits directly to the main branch without turning off the branch protection rules.
> Use admin github token for releaser

- docs/environment.yml
- pyproject.toml
- readthedocs.yml
Added `SKIP_JUPYTER_BUILDER=1` to readthedocs config for the project.
When installing in editable mode locally, node is now optional.
> Make node optional

- jupyter_server/pytest_plugin.py
- jupyter_server/serverapp.py
- jupyter_server/services/contents/filemanager.py
- pyproject.toml
- tests/services/contents/test_api.py
- tests/services/contents/test_config.py
- tests/services/kernels/test_api.py
- tests/services/kernels/test_cull.py
- tests/services/sessions/test_api.py
Make the async contents manager the default, and add deprecation warning when using synchronous contents or kernel managers.
> Clean up handling of synchronous managers

- .github/workflows/downstream.yml
- .github/workflows/python-tests.yml
- tests/extension/test_serverextension.py
This will fail until https://github.com/jupyter/notebook/pull/6616 is merged and released
> Test notebook prerelease

- .github/workflows/python-tests.yml
- jupyter_server/services/contents/checkpoints.py
- tests/conftest.py
- tests/services/contents/test_api.py
- tests/services/contents/test_checkpoints.py
- Install nbconvert prereqs on Ubuntu to increase coverage
- Add explicit tests for all contents managers - found a bug in `AsyncGenericCheckpointsMixin.restore_checkpoint`
> Increase nbconvert and checkpoints coverage

- .github/workflows/integration-tests.yml
- .github/workflows/python-tests.yml
- codecov.yml
- jupyter_server/pytest_plugin.py
- jupyter_server/serverapp.py
- pyproject.toml
- tests/test_utils.py
- tests/unix_sockets/test_serverapp_integration.py
- Add coverage report config to ignore common patterns
- Actually install pandoc on Ubuntu to improve nbconvert coverage
- Add more utils coverage
- Add `shutdown_server` coverage and include integration tests in overall coverage
> More coverage

- docs/source/conf.py
- docs/source/operators/configuring-logging.rst
- docs/source/operators/index.rst
- pyproject.toml
Addresses #684
~(will fail CI until Traitlets `5.2.1` is released)~
* Bump minimum traitlets version from `5.1` to `5.2.1` (not yet released).
* This gives us access to the `logging_config` trait.
* Don't know if you want to bump the traitlets version or just add a note that this is a new feature of Traitlets 5.2.0.
* Note Traitlets 5.2.0 has a couple of bugs so best to wait for 5.2.1 before advertising this.
* Document how to use `logging_config` with Jupyter Server / extension applications.
* Addresses #684
* Provide examples for pointing Jupyter Server & extension application output at a file.
> docs: document the logging_config trait

- jupyter_server/services/contents/filemanager.py
- tests/services/contents/test_manager.py
In working on the Pull Request https://github.com/jupyter/notebook/pull/6609 , I found that the tests for hidden files was broken, so that I fixed the tests and found more problems to fix.
Some mistakes regarding the tests are as follows (for example, see `test_400` in`tests/services/contents/test_manager.py` https://github.com/jupyter-server/jupyter_server/blob/main/tests/services/contents/test_manager.py#L329-L342 ):
- There is the `try ... except` in `with pytest.raises(HTTPError)` , but actually the exception is raised by the `cm.new` before the `try` and never performs the `rename_file`.
- The `old_path` or `new_path` is set to the return value of `cm._get_os_path()` (it seems an absolute path), but I assume that `rename_file` and `delete_file` expects relative paths.
When I fixed …
> Fix rename_file and delete_file to handle hidden files properly

- .github/workflows/integration-tests.yml
- pyproject.toml
- tests/test_serverapp.py
- tests/unix_sockets/test_serverapp_integration.py
Also upload coverage from integration tests
> Add more serverapp tests

- jupyter_server/base/zmqhandlers.py
- jupyter_server/services/kernels/connection/channels.py
> Tornado WebSocketHandler fixup

- jupyter_server/services/kernels/connection/channels.py
Follow-up on #1047. 
This was an oversight in that PR. We should use `handle_outgoing_message` to reply on the websocket.
> Use handle_outgoing_message for ZMQ replies

- jupyter_server/services/kernels/connection/channels.py
- tests/services/kernels/test_connection.py
This exercise found a few bugs in `ZMQChannelsWebsocketConnection`.  
Also, it seems odd to me that `handle_outgoing_message` is defined on the abc but isn't used anywhere.  Was that an oversight @Zsailer?
> Add more websocket connection tests and fix bugs

- jupyter_server/base/handlers.py
- tests/test_handlers.py
Caught a bug in `AuthenticatedFileHandler.get`.  When `.head` is called, it calls `.get` with `include_body=False`.
> Add base handler tests

- .github/workflows/integration-tests.yml
- .github/workflows/python-tests.yml
- pyproject.toml
We were getting the error:
```
==> Detecting CI provider
GitHub Actions CI Detected
Fixing merge commit SHA
==> Preparing upload
==> Processing gcov (disable by -X gcov)
==> Collecting reports
Generating coverage xml reports for Python
Error running `['/Users/runner/hostedtoolcache/Python/3.8.14/x64/bin/python', '-m', 'coverage', 'xml', '-i']`: returncode=1, output=b"Can't read 'pyproject.toml' without TOML support. Install with [toml] extra\n"
- Ignored: [Errno 2] No such file or directory: '/Users/runner/work/jupyter_server/jupyter_server/coverage.xml'
Error: No coverage report found
Tip: See all example repositories: https://github.com/codecov?query=example
```
https://github.com/jupyter-server/jupyter_server/actions/runs/3536103578/jobs/5934829302
> Fix coverage upload

- jupyter_server/serverapp.py
> Defer webbrowser import

- .github/workflows/python-tests.yml
- pyproject.toml
> Add skip-if-exists config

- jupyter_server/services/kernels/connection/channels.py
- jupyter_server/services/kernels/websocket.py
- tests/services/kernels/test_connection.py
Fixes #1103
Fixes https://github.com/jupyterlab/jupyterlab/issues/13481
> Fix kernel WebSocket protocol

- docs/source/operators/security.rst
I guess that change is a left over of notebook extraction?
> Remove left over from notebook

- codecov.yml
- Turn off the github annotations
- Require 50% of new code to be covered (we can still override and merge)
- Show green coverage at 80%
- Wait until most builds have finished before posting the comment
- Wait until all the other builds finish before assigning status
> Tweak codecov settings

- tests/services/kernelspecs/test_api.py
The native kernel is faster, so we'd like to switch the default back in https://github.com/jupyter-server/pytest-jupyter/pull/36.  This change makes us less brittle.
> Make tests less sensitive to default kernel name

- jupyter_server/gateway/managers.py
- tests/test_gateway.py
Lab services issues `/api/kernels` and `/api/sessions` requests every 10 seconds on behalf of its `KernelManager` and `SessionManager` instances, respectively.  When a gateway server is configured, the `/api/kernels` request is forwarded to the gateway server, while the `/api/sessions` request only needs to ensure the kernel model in its list of sessions is still valid (i.e., not culled) - which leads to an additional (but specific) `/api/kernels/<kernel_id>` request.
In highly latent and multi-tenant installations (in which a single gateway is servicing multiple clients) each of these requests adds up.  This pull request eliminates the `/api/kernels/<kernel_id>` request performed on behalf of the client's `/api/sessions` request by treating the set of kernel models maintained via the …
> [Gateway] Remove redundant list kernels request during session poll

- .pre-commit-config.yaml
- jupyter_server/extension/application.py
- pyproject.toml
- tests/services/events/mockextension/__init__.py
Addresses ```warning: `I252` has been remapped to `TID252` ``` error seen in CI.
> Fix lint rule

- jupyter_server/serverapp.py
`jupyter lab list` command failed with error:
```
TypeError: not all arguments converted during string formatting
Call stack:
File "/path/bin/jupyter-lab", line 8, in <module>
sys.exit(main())
File "/path/lib/python3.9/site-packages/jupyter_server/extension/application.py", line 611, in launch_instance
serverapp.start()
File "/path/lib/python3.9/site-packages/jupyter_server/serverapp.py", line 2884, in start
self.start_app()
File "/path/lib/python3.9/site-packages/jupyter_server/serverapp.py", line 2775, in start_app
super().start()
File "/path/lib/python3.9/site-packages/jupyter_core/application.py", line 265, in start
self.subapp.start()
File "/path/lib/python3.9/site-packages/jupyter_server/serverapp.py", line 686, in start
info(url, "::", serverinfo["root_dir"])
```
> Logging message used to list sessions fails with template error

- jupyter_server/serverapp.py
> only write browser files if we're launching the browser

- .github/workflows/python-tests.yml
- jupyter_server/serverapp.py
> Find an available port before starting event loop

- jupyter_server/extension/serverextension.py
Fixes #1134. We can backport this to 1.x once it's merged.
This no longer uses an `ExtensionManager` to load all the extensions as a bunch. Instead, it loads each extension separately, adds a try/catch clause for each individual extension validation, logs the error (if found) for each extension, and doesn't block the validation for other extensions. 
Here is an example of the new output:
```
Config dir: /Users/zsailer/.jupyter
Config dir: /Users/env/etc/jupyter
jupyter_server_terminals enabled
- Validating jupyter_server_terminals...
X Jupyter Server Terminals requires Jupyter Server 2.0+
File "/Users/zsailer/Documents/Work/oss/internal/jupyter_server/jupyter_server/extension/serverextension.py", line 336, in list_server_extensions
extension = …
```
> Raise errors on individual problematic extensions when listing extension

- jupyter_server/serverapp.py
- jupyter_server/services/contents/fileio.py
- jupyter_server/services/contents/filemanager.py
- jupyter_server/services/contents/manager.py
- tests/test_gateway.py
- tests/test_serverapp.py
- tests/test_terminal.py
Reverts jupyter-server/jupyter_server#983
> Revert "Make preferred_dir content manager trait"

- jupyter_server/serverapp.py
- tests/test_serverapp.py
Make skipping the browser open files opt-in.
- fixes #1143
- make `browser_open_file` `allow_none=True`
- this is probably clearer, and wouldn't introduce a new config variable, but `None`s do weird things
> Restore default writing of browser open redirect file, add opt-in to skip

- jupyter_server/serverapp.py
- tests/test_terminal.py
> Fix handling of extension last activity

- jupyter_server/files/handlers.py
- jupyter_server/gateway/managers.py
- jupyter_server/nbconvert/handlers.py
- jupyter_server/serverapp.py
- jupyter_server/services/api/handlers.py
- jupyter_server/services/contents/handlers.py
- jupyter_server/services/contents/manager.py
- jupyter_server/services/kernels/connection/channels.py
- jupyter_server/services/kernels/handlers.py
- jupyter_server/services/kernels/kernelmanager.py
- jupyter_server/services/kernelspecs/handlers.py
- jupyter_server/services/sessions/handlers.py
- jupyter_server/services/sessions/sessionmanager.py
- jupyter_server/view/handlers.py
- tests/services/contents/test_checkpoints.py
- tests/services/contents/test_largefilemanager.py
- tests/services/contents/test_manager.py
- tests/test_gateway.py
It seem to me that hiding the fact that ensure_async is from a dependency is counter productive as it adds an unnecessary level of indirection and hide the jupyter_core dependency.
> Import ensure-sync directly from dependence.

- jupyter_server/serverapp.py
> Remove `end` kwarg after migration from print to info

- jupyter_server/auth/identity.py
- jupyter_server/auth/security.py
- jupyter_server/extension/handler.py
- jupyter_server/extension/manager.py
- jupyter_server/extension/serverextension.py
- jupyter_server/extension/utils.py
- jupyter_server/gateway/managers.py
- jupyter_server/serverapp.py
- jupyter_server/services/contents/checkpoints.py
- jupyter_server/services/contents/manager.py
- jupyter_server/services/kernels/connection/channels.py
- jupyter_server/services/sessions/sessionmanager.py
- jupyter_server/traittypes.py
- jupyter_server/utils.py
- pyproject.toml
For cleaner [tracebacks](https://github.com/henryiii/flake8-errmsg)
> Handle flake8-errmsg

- jupyter_server/extension/manager.py
> Iterate through set of apps in `extension_manager.any_activity` method

- jupyter_server/base/handlers.py
The source code permalink provided in here was broken, likeley due to force pushes in the PR (#671) adding the comment.
https://github.com/jupyter-server/jupyter_server/blob/2a88e2a2c033578b7d72b440c296acbbe80fb398/jupyter_server/base/handlers.py#L229-L241
I'm updating it to reference v2.0.0 instead, which also helps the reader understand when in time this message refers to. Specifically to the first line in this code block:
https://github.com/jupyter-server/jupyter_server/blob/2a88e2a2c033578b7d72b440c296acbbe80fb398/jupyter_server/serverapp.py#L242-L249
> Fix broken link in warning message

- jupyter_server/serverapp.py
- jupyter_server/services/contents/fileio.py
- jupyter_server/services/contents/filemanager.py
- jupyter_server/services/contents/manager.py
- tests/test_gateway.py
- tests/test_serverapp.py
- tests/test_terminal.py
This reverts #1140, reapplying https://github.com/jupyter-server/jupyter_server/pull/983. It then adds compatibility with jupyterlab_server prior to https://github.com/jupyterlab/jupyterlab_server/pull/324, by writing back validated values to the serverapp's trait.
> Reapply preferred_dir fix, now with better backwards compatability

- pyproject.toml
Handles:
```
installing check-wheel-contents...
dist/jupyter_server-2.0.7-py3-none-any.whl: W002: Wheel contains duplicate files:
jupyter_server/static/favicon.ico
jupyter_server/static/favicons/favicon.ico
```
> Fix check release by ignoring duplicate file name in wheel

- jupyter_server/extension/utils.py
Based on some detailed debugging in
https://github.com/2i2c-org/infrastructure/issues/2047 to figure out why a Jupyter Server *process* sometimes takes more than 30s
to start, the primary culprit was server extensions that took multiple seconds to just even import. Thanks to some ad-hoc patching (https://github.com/2i2c-org/infrastructure/issues/2047#issuecomment-1379785520), I was able to figure out which were the slow extensions. This PR emits extension import time as log messages, so this information is *much* more visible.
I also explicitly chose info instead of debug, primarily because I believe it is *very* important to surface this performance information to users, so they can go bug the appropriate extension. Otherwise, it just feels like 'jupyter server is slow!'. This is …
> Log how long each extension module takes to import

- jupyter_server/base/handlers.py
- jupyter_server/gateway/managers.py
- jupyter_server/services/contents/fileio.py
- jupyter_server/services/kernels/kernelmanager.py
- jupyter_server/services/sessions/handlers.py
- jupyter_server/services/sessions/sessionmanager.py
- jupyter_server/utils.py
- tests/services/sessions/test_manager.py
- tests/utils.py
This also add some typing here and there, and extend one of the console warning to log an exception when there is an error.
My main concern is that get_kernel_env need to become async.
> Set JPY_SESSION_NAME to full notebook path.

- jupyter_server/services/contents/manager.py
- tests/test_serverapp.py
Also includes a regression test.
> Fix preferred_dir for sync contents manager

- jupyter_server/extension/manager.py
Without this, the log messages printed in
https://github.com/jupyter-server/jupyter_server/pull/1171 don't actually make it out. Whoops!
LoggingConfigurable inherits from HasTraits, and sets up Logging appropriately so we can have a log passed through.
> Pass in a logger to get_metadata

- jupyter_server/extension/manager.py
- tests/extension/test_manager.py
- only load metadata if a given extension package is enabled (closes #1177)
- module will be None, extension points will be empty if disabled. Version will be empty, though we could look it up _most_ of the time via `importlib_metadata` (module name != package name, etc.). I'm not sure how relevant the version number is for disabled extensions, though.
- unify use of traitlets, removing redundant use of public properties exposing identical private attributes, when public attributes will do (no change to api).
> Only load enabled extension packages

- jupyter_server/gateway/managers.py
- tests/test_gateway.py
Starting with the 2.0.2 release of jupyter_server, every entry in the `resources` field of a kernelspec reported by the kernel gateway is assumed to be a path relative to the kernel gateway URL starting with `/kernelspecs`).
However, this assumption is not documented anywhere in the REST API doc (as far as I can tell), and I have a kernel gateway server that uses the resources object to report additional URLs that are not relative to `/kernelspecs/`.
With that combination, any attempts to use this kernel gateway with a version newer than 2.0.2 results in the following failure trace:
```
Traceback (most recent call last):                                                                                                                                            
File …
```
> Don't assume that resources entries are relative

- examples/simple/webpack.config.js
- jupyter_server/services/sessions/sessionmanager.py
- Force webpack to use a supported algorithm for hashing
- Fix some docstrings in `sessionmanager.py`.
> Fix docs and examples

- jupyter_server/extension/manager.py
- jupyter_server/nbconvert/handlers.py
- jupyter_server/serverapp.py
- jupyter_server/services/contents/filemanager.py
And use exc_info=True instead of a separate log.exception to make sure the tb is attached to the right log message.
Using `%s` can have issue when logging error as it may hide informations like the type of exception. If for example you have an assertion error, %s will give you the empty string, which is not informative.
On the other hand, %r will _at least_ give you `AssertionError()`, which is a start.
> Use repr in logging for exception.

- jupyter_server/gateway/managers.py
- jupyter_server/services/kernels/kernelmanager.py
- Use `ensure_async()` where appropriate
- Fix type checking
> Updates for client 8

- jupyter_server/serverapp.py
This change was made in #460, but somehow it was not here.
> Delete the extra "or" in front of the second url

- jupyter_server/serverapp.py
When I try to deploy the jupyterlab server in an environment with IPV6 address, the server fail to start with stack trace like:
```
File "/opt/conda/bin/jupyter-lab", line 10, in <module>
sys.exit(main())
File "/opt/conda/lib/python3.10/site-packages/jupyter_server/extension/application.py", line 607, in launch_instance
serverapp = cls.initialize_server(argv=args)
File "/opt/conda/lib/python3.10/site-packages/jupyter_server/extension/application.py", line 577, in initialize_server
serverapp.initialize(
File "/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py", line 113, in inner
return method(app, *args, **kwargs)
File "/opt/conda/lib/python3.10/site-packages/jupyter_server/serverapp.py", line 2550, in initialize …
```
> Support IPV6 in _find_http_port()

- jupyter_server/log.py
replaces `?token=abc123` with `?token=[secret]` in logs to avoid logging things like auth tokens.
adapted [from jupyterhub](https://github.com/jupyterhub/jupyterhub/blob/7b2c89d46cf42c37c21eef689574ab915cbb26b9/jupyterhub/log.py#L69-L93)
> Redact tokens, etc. in url parameters from request logs

- jupyter_server/log.py
replaces `?token=abc123` with `?token=[secret]` in logs
(cherry picked from commit 968c56c8c69aa545f7fe93243331fe140dac7c90)
> Backport PR #1212: Redact tokens, etc. in url parameters from request  logs

- jupyter_server/base/handlers.py
- jupyter_server/gateway/handlers.py
- tests/test_gateway.py
The `APIHandler.finish()` method unconditionally overrides the header's `Content-type` to `application/json` despite the `GatewayResourceHandler` setting it to a mime-type corresponding to the resource's extension.
This pull request enables the caller to indicate the `ContentType` that should be set into the header in `APIHandler.finish()` where `application/json` is the default if no content type is specified.
Resolves: #216
> Ensure content-type properly reflects gateway kernelspec resources

- jupyter_server/services/contents/filemanager.py
- jupyter_server/services/contents/manager.py
- tests/services/contents/test_api.py
- tests/services/contents/test_manager.py
Enable users to copy both files and directories
Currently, if users try copying a directory, an error will thrown backing saying "Can't Copy directories". 
- The copy option in the right click menu, was enabled for directories. 
- 
- The copy directory functionality has been added to both the FileContentsManager and AsyncFileContentsManager
- Users can copy folders up to 100 MB,
- The actual limit for copying directories before a timeout occurs is 500MB, but without a loading indicator, if a user tries to copy a folder that is near 500MB, jupyterlab  will seem like its frozen, since its not clear whether the copy operation is complete or in progress. 
- if we can add a loading indicator in the future to jupyterlab, then we would be able to increase the limit of copying folders to 500 MB …
> Enable users to copy both files and directories

- jupyter_server/serverapp.py
- tests/test_serverapp.py
The `_root_dir_set` flag prevents deprecated `notebook_dir` config from being loaded at a higher priority than newer `root_dir` config.
This config is relatively likely to be set, as `notebook_shim` means that legacy config, which should not be removed, is still loaded into ServerApp, so anyone who still has notebook config present for working with the older server will still get this config set on the new server, and it should be ignored in favor of newer config.
> Fix priority of deprecated NotebookApp.notebook_dir behind ServerApp.root_dir (#1223

- jupyter_server/base/handlers.py
- jupyter_server/files/handlers.py
- jupyter_server/services/contents/filemanager.py
- jupyter_server/services/contents/handlers.py
- tests/base/test_handlers.py
- tests/services/contents/test_api.py
- tests/services/contents/test_manager.py
- tests/test_files.py
Fixes #1224. Also adds regression tests, and enables some tests that were skipped on Windows, but did not need to? Maybe they were just passing locally for me?
> Optimize hidden checks

- jupyter_server/gateway/gateway_client.py
Feature for https://github.com/jupyter-server/jupyter_server/issues/1231. With this change, error messages from Enterprise Gateway will be propagated through Jupyter Server to the frontend. Looking through the Enterprise Gateway code, it seems that the JSON payload returned should only contain a `reason` field or a `message` field (or both possibly). See the code for the `log_and_raise` method of the processproxy [here](https://github.com/jupyter-server/enterprise_gateway/blob/7effcb59d3e8c13cb4b95b9f6f0f22cbf08f93c0/enterprise_gateway/services/processproxies/processproxy.py#L998-L1020) where the `reason` field is populated, and also see the [swagger spec](https://github.com/jupyter-server/enterprise_gateway/blob/7effcb59d3e8c13cb4b95b9f6f0f22cbf08f93c0/enterprise_gateway/services/api/swag …
> Added error propagation to gateway_request function

- jupyter_server/kernelspecs/handlers.py
This is the last set of request handlers that are not async enabled in Jupyter Server. 
With this change, an async KernelSpecManager is possible. 🚀
> Enable KernelSpecResourceHandler to be async

- docs/source/operators/public-server.rst
- docs/source/operators/security.rst
While reading up on identity providers and authorizers (great information btw!), I found a few words that were meant to be italicized but the markdown character (`_`) was used instead of the rST character (`*`).  This PR merely fixes those.  I grepped the rest of the docs and found a couple of other instances in the public-server doc.
> Fix italics in operators security sections

- jupyter_server/serverapp.py
- jupyter_server/services/kernels/handlers.py
- jupyter_server/services/kernels/websocket.py
During the [2.x refactor of kernel websocket management](https://github.com/jupyter-server/jupyter_server/pull/1047), the file from which the websocket handler is registered changed.  The presents problems for applications that extend or leverage services and handlers from Jupyter Server (like Kernel Gateway and Enterprise Gateway, and perhaps other third-party applications).  As a result, those applications must account for this this file which presents problems for supporting both JupyterServer 1.x and 2.x.
This change moves the websocket handler registration back to the `services/kernels/handlers.py` file so that "extending applications" don't require changes  in their registration code to use JS 2.
> Register websocket handler from same module as kernel handlers

- jupyter_server/gateway/managers.py
- tests/test_gateway.py
This change updates the GatewayMappingKernelManager class to double check when it believes kernels may have been culled in the Gateway server.
Previously, if a known kernel was missing from the list of kernels returned by the Gateway server, then the GatewayMappingKernelManager class assumed it was culled. With this change, it will first attempt to fetch
the kernel from the Gateway server and only treat it as culled if this second check also fails.
This increases reliability in the scenario of a Gateway server erroneously returning a partial list of kernels due to things like bugs around race conditions for newly created kernels, or transient network errors when combining results from multiple backends.
> Gateway manager retry kernel updates

- .readthedocs.yaml
Version 2.0 of urllib3 was just released which fails if used against any version of python built against a version of the OpenSSL library older than 1.1.1 (see discussion [here](https://github.com/urllib3/urllib3/issues/2168))
That seems to include all versions of Python older than 3.9.
That change triggers the read the docs builds to fail when running sphinx with a message of the form:
```
Running Sphinx v6.2.1
File "/home/docs/checkouts/readthedocs.org/user_builds/jupyter-server/envs/1267/lib/python3.8/site-packages/sphinx/registry.py", line 442, in load_extension
mod = import_module(extname)
File "/home/docs/checkouts/readthedocs.org/user_builds/jupyter-server/envs/1267/lib/python3.8/importlib/__init__.py", line 127, in import_module
return …
```
> Use Python 3.9 for the readthedocs builds

- jupyter_server/services/kernels/connection/base.py
- jupyter_server/services/kernels/connection/channels.py
This change moves the `kernel_websocket_protocol` flag out from the sub-class `ZMQChannelsWebsocketConnection` and into its base class `BaseKernelWebsocketConnection` so that it is automatically available to any other sub classes of `BaseKernelWebsocketConnection`.
> Make the kernel_websocket_protocol flag reusable.

- jupyter_server/base/handlers.py
- jupyter_server/serverapp.py
- tests/base/test_handlers.py
- tests/test_serverapp.py
As mentioned in https://github.com/jupyterlab/jupyterlab/issues/10273 and https://github.com/jupyterlab/jupyterlab/issues/14124, JupyterLab now uses hashes for the javascript assets.
This PR allows to serve static files as immutable to avoid server requests (when the static files have `no-cache` header), by setting up the setting _"static_immutable_cache"_.
*Additional context:*
Discussed in weekly meeting https://github.com/jupyter-server/team-compass/issues/45#issuecomment-1525993398
> Allows immutable cache for static files in a directory

- jupyter_server/gateway/connections.py
instantiating Future at import will often not work because no event loop is running
> Don't instantiate an unused Future in gateway connection trait

- jupyter_server/serverapp.py
- pyproject.toml
- tests/test_serverapp.py
instead of logging, which goes to stderr and is often prefixed and/or filtered by log levels
regression introduced in #1114 because the linter gave some bad advice.
I added an ignore for the print lint in app files, since print's the right way to produce output on stdout in general, not logging. I'd probably choose disabling it globally, but didn't want to go that far here.
closes #1273
> Write server list to stdout

- tests/extension/test_entrypoint.py
DeprecationWarning: script_runner commands should be passed as a single sequence, not as multiple arguments.
Replace `script_runner.run(a, b, c)` calls with
`script_runner.run([a, b, c])`
> Fix DeprecationWarning from pytest-console-scripts

- .github/workflows/python-tests.yml
- pyproject.toml
- tests/test_terminal.py
Update pandoc and add flaky test for terminal culling.
> Handle test failures

- jupyter_server/gateway/gateway_client.py
Add missing gateway event 
- on successful (good) communication with EG
- on all error conditions
This is a solution for the issue - https://github.com/jupyter-server/jupyter_server/issues/1287
> Add missing events to gateway client

- jupyter_server/base/handlers.py
Proposed fix for https://github.com/jupyter-server/jupyter_server/issues/1293
Use the newer format for checking authenticated user. `_user_cache` no longer exists, so api_last_activity is never being updated.
> Reference current_user to detect auth

- docs/source/operators/public-server.rst
- pyproject.toml
**PR Summary**:
The PR contains a simple fix to broken hyperlink pointing to Tornado. Relevant docs can be found [here](https://jupyter-server.readthedocs.io/en/latest/operators/public-server.html). As you might see, it points to:
> withfoundtohttp://www.tornadoweb.org/en/stable/
> docs: fix broken hyperlink to Tornado

- jupyter_server/event_schemas/kernel_actions/v1.yaml
- jupyter_server/services/kernels/kernelmanager.py
- pyproject.toml
Fix for https://github.com/jupyter-server/jupyter_server/issues/1299
> Make kernel_id as a conditional optional field

- jupyter_server/services/api/api.yaml
we've had it [since IPython 3.0](https://github.com/ipython/ipython/pull/6654), might as well mention it.
> Add root `/api/` endpoint to REST spec

- jupyter_server/base/handlers.py
reported by @rcthomas
otherwise, using `GET /api/` as a healthcheck will cause the server to never appear idle.
> accessing API version should not count as activity

- jupyter_server/services/events/handlers.py
- tests/services/contents/test_manager.py
- tests/services/events/test_api.py
`expected_http_error` returns `bool | None` to be tested.
https://github.com/jupyter-server/jupyter_server/blob/c5dc0f696f376e1db5a9a0cbcebb40a0bf98875c/tests/utils.py#L24-L45
> Assert return value of `expected_http_error`

- jupyter_server/serverapp.py
- jupyter_server/services/kernels/connection/channels.py
- pyproject.toml
Needs https://github.com/jupyter/jupyter_client/pull/961.
This will make it possible for JupyterLab to connect to a kernel that it did not launch, for instance a kernel launched by Jupyter Console:
https://github.com/jupyter-server/jupyter_server/assets/4711805/1555239f-c441-4740-9e7e-376b5a9d751c
> Support external kernels

- jupyter_server/serverapp.py
if shutdown is confirmed with ctrl-C twice and shutdown took more than 5s, logs would erroneously show "resuming operation..." before finally shutting down.
> Avoid showing "No answer for 5s" when shutdown is slow

- examples/simple/simple_ext1/application.py
- examples/simple/simple_ext2/application.py
- jupyter_server/auth/identity.py
- jupyter_server/extension/manager.py
- jupyter_server/gateway/connections.py
- jupyter_server/gateway/gateway_client.py
- jupyter_server/gateway/managers.py
- jupyter_server/serverapp.py
- jupyter_server/services/contents/filecheckpoints.py
- jupyter_server/services/contents/filemanager.py
- jupyter_server/services/contents/manager.py
- jupyter_server/services/events/handlers.py
- jupyter_server/services/kernels/connection/channels.py
- jupyter_server/services/kernels/kernelmanager.py
- jupyter_server/traittypes.py
- pyproject.toml
- tests/extension/mockextensions/app.py
There are still a few edge cases, identified in https://github.com/ipython/traitlets/issues/871, but we already caught some places that could have been `None.`
> Update typings for traitlets 5.10

- jupyter_server/services/contents/fileio.py
- jupyter_server/services/contents/filemanager.py
- tests/services/contents/test_fileio.py
closes issue [jupyter/notebook#857](https://github.com/jupyter/notebook/issues/857)
Changes made: added **self.log.debug("Reading path from disk: %s", path)** in filemanager.py in jupyter_server
> Added Logs for get_os_path closes issue

- jupyter_server/gateway/gateway_client.py
- tests/test_gateway.py
Prior to the `2.8.0` release, Gateway token renewers would be run regardless of the value of the initial auth token configured with the Gateway client.
However, that initial value could potentially be `None`, and token renewers are not required to support that as a value for their `auth_token` parameter. This meant that token renewers might be called with a value they do not support.
The `2.8.0` release fixed that issue by only calling token renewers if the `auth_token` value was truthy. However, this introduced a regression because the default value for auth tokens is the empty string, which is not truthy but which *is* a valid string value (and, as such, is expected to be supported by token renewers).
This change fixes that by calling token renewers as long as the `auth_token` value is …
> Run Gateway token renewers even if the auth token is empty.

- jupyter_server/services/kernels/kernelmanager.py
- tests/services/kernels/test_cull.py
This change enables users to configure culling behavior per kernel by configuring the timeout using kernel spec. This would provide users flexibility to configure timeout values per kernel based on their use cases
> Ability to configure cull_idle_timeout with kernelSpec

- jupyter_server/services/sessions/sessionmanager.py
This rely on jupyter/jupyter_client#987 and fixes ipython/ipykernel#1102 When a user rename the notebook in the UI, it will update the kernel env, so that the ``__session__`` variable reflect the new name on the next restart.
It _does_ seem that each rename of a notebook in JupyterLab creates 4 update_session (2 with name, and 2 with path), but that does not seem to be a problem in this repository.
> Update kernel env to reflect changes in session.

- .pre-commit-config.yaml
- docs/source/conf.py
- jupyter_server/base/handlers.py
- jupyter_server/gateway/gateway_client.py
- jupyter_server/serverapp.py
- jupyter_server/services/kernels/connection/channels.py
- jupyter_server/utils.py
- pyproject.toml
- tests/auth/test_identity.py
- tests/services/sessions/test_manager.py
> Update typings and fix tests

- jupyter_server/_tz.py
- pyproject.toml
- tests/test_gateway.py
> Clean up config and address warnings

- jupyter_server/services/sessions/sessionmanager.py
> Update kernel env to reflect changes in session

- .pre-commit-config.yaml
- jupyter_server/services/contents/handlers.py
- tests/services/contents/test_manager.py
this addresses #1328. This works based on my testing but I'm more than happy to make structural changes to clean the code up. I'm admittedly not very well versed in tornado. Thanks in advance for feedback :)
>  ContentsHandler return 404 rather than raise exc

- jupyter_server/_tz.py
- jupyter_server/auth/decorator.py
- jupyter_server/auth/identity.py
- jupyter_server/base/handlers.py
- jupyter_server/config_manager.py
- jupyter_server/extension/application.py
- jupyter_server/extension/handler.py
- jupyter_server/extension/serverextension.py
- jupyter_server/gateway/connections.py
- jupyter_server/gateway/gateway_client.py
- jupyter_server/gateway/handlers.py
- jupyter_server/gateway/managers.py
- jupyter_server/i18n/__init__.py
- jupyter_server/serverapp.py
- jupyter_server/services/api/handlers.py
- jupyter_server/services/config/manager.py
- jupyter_server/services/contents/filemanager.py
- jupyter_server/services/events/handlers.py
- jupyter_server/services/kernels/connection/abc.py
- jupyter_server/services/kernels/connection/base.py
- jupyter_server/services/kernels/connection/channels.py
- jupyter_server/services/kernels/kernelmanager.py
- jupyter_server/services/sessions/sessionmanager.py
- jupyter_server/traittypes.py
- jupyter_server/utils.py
- pyproject.toml
Fix untyped `utcfromtimestamp` and handle "type-arg" and "no-any-return" codes.
> Add more typings

- docs/source/developers/contents.rst
- jupyter_server/services/contents/fileio.py
- jupyter_server/services/contents/filemanager.py
- jupyter_server/services/contents/handlers.py
- jupyter_server/services/contents/manager.py
- tests/services/contents/test_api.py
- tests/services/contents/test_fileio.py
- tests/services/contents/test_manager.py
Currently, JupyterLab determines whether a file has been manually modified by another client or user by **comparing timestamps**. 
In this way, JupyterLab can prompt the user whether to overwrite the file on disk with the file on the current page, or discard the file on the current page.
This usually performs well on local storage. However, when users use remote storage such as nfs, samba, the modified time of the file is not reliable due to things such as network latency or storage back-end implementations. To solve this problem, https://github.com/jupyterlab/jupyterlab/pull/15037 tries to compare content by comparing them one by one, but this definitely increases the network overhead and client burden.
I propose that this PR to **add md5 parameter to the contents API**. Any client can …
> Support get file(notebook) md5

- jupyter_server/services/api/api.yaml
Update the api documentation for https://github.com/jupyter-server/jupyter_server/pull/1363.
> Update api docs with md5 param

- .github/workflows/downstream.yml
- docs/source/developers/contents.rst
- jupyter_server/services/api/api.yaml
- jupyter_server/services/contents/filecheckpoints.py
- jupyter_server/services/contents/fileio.py
- jupyter_server/services/contents/filemanager.py
- jupyter_server/services/contents/handlers.py
- jupyter_server/services/contents/manager.py
- tests/services/contents/test_api.py
- tests/services/contents/test_fileio.py
- tests/services/contents/test_manager.py
- tests/services/contents/test_manager_no_hash.py
Resolves #1366 https://github.com/mwouts/jupytext/issues/1165 https://github.com/ploomber/ploomber/issues/1144
Sorry for the breaking changes to the API. This should allow downstream optional support for md5.
> Change md5 to hash and hash_algorithm, fix incompatibility

- jupyter_server/services/contents/fileio.py
This catches a subset of cases in #1368 where truly invalid paths (e.g. `"foo\0"`) raise ValueError, where most of our error handling may only catch OSError.
> avoid unhandled error on some invalid paths

- jupyter_server/auth/authorizer.py
- jupyter_server/auth/decorator.py
- tests/auth/test_authorizer.py
Add support for asynchronous Authorizers.
This is feature additive—it shouldn't affect standard, synchronous authorizers. This enables folks to make the `is_authorized` method asynchronous which is particularly useful for fetching authorization status from an external auth provider.
> Support async Authorizers

- jupyter_server/extension/utils.py
avoids unnecessary noise most of the time, while still reporting when things are slow enough to cause a problem.
> log extension import time at debug level unless it's actually slow

- .pre-commit-config.yaml
- examples/simple/pyproject.toml
- jupyter_server/auth/security.py
- jupyter_server/utils.py
- pyproject.toml
https://astral.sh/blog/ruff-v0.1.8#formatting-code-snippets-in-docstrings
> Use ruff docstring-code-format

- .readthedocs.yaml
- fixes #1378
This _won't_ trigger on the per-PR-push docs build, so kinda needs to be merged to `main` be fully tested, with a quick revert if necessary.... or going through the hassle of making a fake site.
> Enable htmlzip and epub on readthedocs

- jupyter_server/services/contents/filemanager.py
Fixing a minor typo introduced in https://github.com/jupyter-server/jupyter_server/pull/1291 which is visible in user-facing messages as seen in https://github.com/jupyterlab/jupyterlab/issues/15589
> Fix a typo in error message

- jupyter_server/gateway/connections.py
Fixes #1310 
Currently, ws subprotocols should be the same for notebook client and gateway since there is no serializer/deserializer between the 2 streams if subprotocols differ.
> Force legacy ws subprotocol when using gateway

- tests/test_gateway.py
Currently using pytest-xdist sometimes fails because of `test_gateway_request_with_expiring_cookies` which has a changing parameter: `expire_param` will be computed as 180 seconds in the future at file load time. But when using xdist each thread computes its own value for this parameter and it may happen that different threads have different parameters, which xdist doesn't support.
Here I change the test so the parameter is just 180, and the actual timestamp for the expiration argument is computed inside the test. With this single change, using pytest-xdist works fine.
> Fix test param for pytest-xdist

- .github/workflows/downstream.yml
Jupytext's documentation is now included in the Jupytext package (from `jupytext>=1.16.0`) so the `ignore` commands should not be needed anymore.
> Simplify the jupytext downstream test

- jupyter_server/base/handlers.py
It is used in a cast on line 617, rather than just a type annotation. Without this, requests fail with:
```
[E 2024-01-09 18:30:53.736 SingleUserNotebookApp web:1871] Uncaught exception GET /user/yuvi.panda@utoronto.ca/lab (10.1.0.10)
HTTPServerRequest(protocol='https', host='jupyter.utoronto.ca', method='GET', uri='/user/yuvi.panda@utoronto.ca/lab', version='HTTP/1.1', remote_ip='10.1.0.10')
File "/opt/conda/lib/python3.11/site-packages/tornado/web.py", line 1765, in _execute
result = await result  # type: ignore
^^^^^^^^^^^^
File "/opt/conda/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 616, in prepare
user = User(self.get_current_user())
^^^^
NameError: name 'User' is not defined
```
> Import User unconditionally

- jupyter_server/gateway/gateway_client.py
log formatting was inconsistent with `e` passed both as a format argument _and_ via f-string, but only expected in the f-string, resulting in [Bad Message errors](https://discourse.jupyter.org/t/failed-to-connect-jupyter-enterprise-gateway-from-jupyterhub/23319)
also avoided extraneous calls to `.instance()` by storing it in a local variable first time it's accessed
> Fix log arguments for gateway client error

- jupyter_server/services/contents/largefilemanager.py
- pyproject.toml
- tests/conftest.py
- tests/extension/test_app.py
- tests/test_gateway.py
Address all but `add_callback_from_signal`, which will be handled by #1362.
I isolated the socket open problems with:
```python
@pytest.fixture(autouse=True)
def gc_cleanup():
yield
import gc
gc.collect()
```
> Improve warning handling

- jupyter_server/serverapp.py
"Shutdown" is a noun. "Shut down" is a verb. I don't like seeing this error when I shut down a server so I'm fixing it :)
> fix "Shutdown" -> "Shut down"

- jupyter_server/serverapp.py
Hi all :wave:
I needed to configure the Tornado `websocket_ping_interval` and `websocket_ping_timeout` settings for a deployment (see [Tornado docs](https://www.tornadoweb.org/en/stable/websocket.html#tornado.websocket.WebSocketHandler)) but couldn't see how to do so.
This PR adds configurable traits for these two ping configurations with `None` defaults to match the current behaviour (i.e. don't send heartbeat pings).
Questions:
1. Is this the right approach? Apologies if I've overlooked something.
2. Should the default be `None` or would it make sense to send heartbeat pings by default?
> websockets: add configurations for ping interval and timeout

- jupyter_server/serverapp.py
Passing `--ServerApp.preferred_dir` warns:
```
FutureWarning: ServerApp.preferred_dir config is deprecated in jupyter-server 2.0. Use FileContentsManager.preferred_dir instead
return self._get_trait_default_generator(names[0])(self)
```
This is the case since https://github.com/jupyter-server/jupyter_server/pull/1162 see:
https://github.com/jupyter-server/jupyter_server/blob/62f4ca250c945dc8953f4d7e5c6f99b516279730/jupyter_server/services/contents/filemanager.py#L79-L84
but this is not documented. This PR adds the warning to trait description for it to be picked up by the docs.
Of note this will not affect the description of the other trait as it is redefined in:
https://github.com/jupyter-server/jupyter_server/blob/62f4ca250c945dc8953f4d7e5c6f99b516279730/jupyter_server/services/contents/ …
> Add deprecation note for `ServerApp.preferred_dir`

- jupyter_server/serverapp.py
Fixes #943
Fix color in windows log console with colorama. Screenshots below are on Windows.
Before:
After:
> Fix color in windows log console with colorama

- jupyter_server/extension/utils.py
Presumably this docs reference to `_jupyter_server_extension_paths` should be `_jupyter_server_extension_points`?
> Replace _jupyter_server_extension_paths in apidocs

- jupyter_server/auth/decorator.py
- jupyter_server/auth/login.py
- jupyter_server/auth/logout.py
- jupyter_server/base/handlers.py
- jupyter_server/base/websocket.py
- jupyter_server/extension/application.py
- jupyter_server/serverapp.py
- jupyter_server/services/api/handlers.py
- jupyter_server/services/contents/handlers.py
- jupyter_server/services/events/handlers.py
- jupyter_server/services/kernels/websocket.py
- jupyter_server/utils.py
- pyproject.toml
- tests/base/test_handlers.py
- tests/base/test_websocket.py
- tests/extension/test_handler.py
- tests/test_serverapp.py
Opening a draft for early feedback on naming and implementation.
Closes #389
Builds upon @yuvipanda's idea of using `prepare` method as described in https://github.com/jupyter-server/jupyter_server/issues/1012#issuecomment-1926355878.
- adds `ServerApp.allow_unauthenticated_access` traitlet (True by default for backwards compatibility)
- adds `@allow_unauthenticated` decorator, an opposite of Torando's `@web.authenticated`
- if `allow_unauthenticated_access` is False rejects requests to endpoints which do not have `@allow_unauthenticated` decorator for any non-authenticated user
- maybe make it a runtime warning?
- maybe also add a runtime warning if any handlers which inherit directly from `web.RequestHandler` rather than `AuthenticatedHandler`/`JupyterHandler` get registered with the …
> Add an option to have authentication enabled for all endpoints by default

- .github/workflows/prep-release.yml
- .github/workflows/publish-changelog.yml
- .github/workflows/publish-release.yml
See https://github.com/jupyter-server/jupyter_releaser/pull/557 for context.
Updates us to use:
- A GitHub App credentials instead of admin token
- PyPI trusted publishing
- Allow for silent releases for security releases
I have configured trusted publishing, release environment, and Ruleset behavior for branches and tags.
> Update release workflows

- pyproject.toml
We'll need https://github.com/box/flaky/pull/199 before flaky is compatible.
> Pin to Pytest 7

- jupyter_server/config_manager.py
Hi,
Thanks for merging my earlier patch! 
Please see the comments here from @manics and @krassowski here (https://github.com/jupyterlab/jupyterlab_server/pull/444) on a similar patch for jupyterlab_server.  There are reasonable arguments to be made for continuing to crash on invalid JSON.  
I've prepared this PR which preserves the previous behavior and only ignores the page_config.json file if it's zero-length.
> Ignore zero-length page_config.json, restore previous behavior of crashing for invalid JSON

- jupyter_server/templates/page.html
this was added to make transferrable login more convenient [long ago](https://github.com/jupyter/notebook/issues/2094), but persisting passwords are the way to go these days, and this isn't the right thing to do in e.g. jupyterhub
ref: https://discourse.jupyter.org/t/is-it-possible-to-avoid-exposing-token-in-get-parameter-in-jupyterhub/24367
This is not a vulnerability, just an improvement in where we pass tokens and when.
> don't include token in dashboard link, when available

- examples/simple/README.md
README-provided script should `cd` into `jupyter_server` before `examples/simple`.
Thanks for considering my PR! :)
> Update simple extension README to cd into correct subdirectory

- docs/source/conf.py
- docs/source/contributors/team-meetings.rst
- docs/source/developers/extensions.rst
- docs/source/index.rst
- docs/source/other/links.rst
- docs/source/users/help.rst
I thought it would be good to list some examples of Jupyter Server extensions on the website.
This could help:
* Make folks aware of the multifaceted applications that Jupyter Server is capable of supporting (much more than just notebooks!).
* Provide a handy reference for extension developers (I found the Jupyter Lab source code an invaluable resource).
* Raise awareness of the extensions already out there (I'm sure there are more that I'm not aware of).
I've listed the server extensions I'm aware of, including my own if you're happy to list it, in descending order of GH stars along with their GH project descriptions. Let me know if there are others I should add. My suggestion is to keep it to actively maintained Jupyter Server extensions (not downstream extensions e.g. Jupyter Lab …
> docs: list server extensions

- docs/source/conf.py
Small quality of life improvement:
- Adds a link icon in the navigation bar
- Adds Edit on GitHub link
> Link to GitHub repo from the docs

- jupyter_server/services/contents/fileio.py
The following is causing excessive logging and polluting the log file making it hard to troubleshoot issues based on log outputs.
> Removing excessive logging from reading local files

- examples/simple/README.md
- examples/simple/simple_ext1/__init__.py
- examples/simple/simple_ext11/__init__.py
- examples/simple/simple_ext2/__init__.py
The simple examples were using the deprecated `_jupyter_server_extension_paths`
> Update simple extension examples: _jupyter_server_extension_points

- jupyter_server/serverapp.py
Fixes https://github.com/jupyter-server/jupyter_server/issues/1432
> Update documentation for `cookie_secret`

- jupyter_server/services/kernels/kernelmanager.py
Fixes #1436
This is mostly to guard users posting debug logs online from exposing secrets which they may have in their environment
> Do not log environment variables passed to kernels

- jupyter_server/gateway/connections.py
- tests/test_gateway.py
Fixes: https://github.com/jupyter-server/jupyter_server/issues/1439
Pass HTTP query param session_id during Websocket channel connection.
Example:
```
GET /api/kernels/342eba8f-aa8c-47a9-8fee-8541cee8ddfe/channels
```
vs
```
GET /api/kernels/342eba8f-aa8c-47a9-8fee-8541cee8ddfe/channels?session_id=4feb3f46-4e83-4fba-bebd-3aba95e96fc0 
```
> Pass session_id during Websocket connect

- jupyter_server/services/kernels/kernelmanager.py
- tests/services/kernels/test_cull.py
- tests/services/kernels/test_execution_state.py
- tests/test_utils.py
This PR makes two adjustments/enhancements for the way kernel execution state is tracked:
1. Distinguish between "busy"/"idle" status messages with different parent IDs.
A "busy" or "idle" status message is not sent in isolation, but rather in response to a specific parent message, and
the kernel might still be busy with one parent message even after reporting that it is done (e.g. has an "idle" status)
with a different parent message.
Accordingly, the overall kernel execution state is only switched to "idle" once all previously seen "busy" status
messages have had a corresponding "idle" message sent with the same parent message ID.
2. Distinguish between different types of parent message when determining whether or not the overall kernel is "busy".
Not every message type corresponds to a …
> Improve the busy/idle execution state tracking for kernels.

- jupyter_server/serverapp.py
ensures `jpserver_extensions` set in `make_serverapp` is preserved after loading config files in `ServerApp.initialize`.
closes https://github.com/jupyterhub/jupyterhub/issues/4859
Repro:
```python
c.ServerApp.jpserver_extensions = {"anything": False}
```
```python
from jupyter_server.extension.application import ExtensionApp
def _jupyter_server_extension_points():
return [{"module": __name__, "app": TestExtension}]
class TestExtension(ExtensionApp):
name = "tester"
if __name__ == "__main__":
TestExtension.launch_instance()
```
and run:
```
python3 testext.py --config ./jupyter_server_config.py
```
which results in:
```
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File …
```
> don't let ExtensionApp jpserver_extensions be overridden by config

- jupyter_server/prometheus/metrics.py
- jupyter_server/serverapp.py
- Allows for collection of jupyter server version as a prometheus metric, and filtering of various other metrics based on server version.
- Builds on top of conventions in other servers that expose version (or build) info. For example, kubernetes puts out this metric:
> kubernetes_build_info{build_date="2024-09-09T04:15:23Z", compiler="gc",
> git_commit="fa081458abcdbbc3ddfc3f99546ae5ea45aece17", git_tree_state="clean",
> git_version="v1.29.8-gke.1700", go_version="go1.22.5 X:boringcrypto",
> instance="10.128.0.50:443", job="kubernetes-apiservers", major="1", minor="29",
> platform="linux/amd64"}
Most of these parameters are not particularly relevant to us, but version is. So this PR only adds version - future labels can be added as needed.
- Fix circular import of …
> Add prometheus metric with version information

- jupyter_server/prometheus/metrics.py
- jupyter_server/serverapp.py
Follow-up to https://github.com/jupyter-server/jupyter_server/pull/1467.
> Add prometheus info metrics listing server extensions + versions

- jupyter_server/prometheus/metrics.py
- jupyter_server/serverapp.py
This exposes some of the info from /api/status in the prometheus metrics endpoint, so they can be scraped over time and queried.
- Server started timestamp, so we can easily see how long servers have been running
- Last activity timestamp, so we can see when users were actually active
- User activity duration (in seconds), so we can more easily build reports of how long users are actually active over time.
All these would be very helpful in JupyterHub environments.
Follow-up to https://github.com/jupyter-server/jupyter_server/pull/1470
> prometheus: Expose 3 activity metrics

- jupyter_server/services/events/handlers.py
- tests/services/events/test_api.py
Currently if a `POST` is made to `/api/events` with a well-formed event that has a schema that hasn't been registered with the `event_logger`, the REST API returns an HTTP 500 error, but in every case I could find where an exception is raised, it comes from bad input, so it should be an HTTP 400 error.
**depends on:** https://github.com/jupyter/jupyter_events/pull/101
> Return HTTP 400 when attempting to post an event with an unregistered schema

- jupyter_server/log.py
- jupyter_server/serverapp.py
Since this records a series of metrics for each HTTP handler class, this quickly leads to an explosion of cardinality and makes storing metrics quite difficult. For example, just accessing the metrics endpoint creates the following 17 metrics:
```
http_request_duration_seconds_bucket{handler="jupyter_server.base.handlers.PrometheusMetricsHandler",le="0.005",method="GET",status_code="200"} 9.0
http_request_duration_seconds_bucket{handler="jupyter_server.base.handlers.PrometheusMetricsHandler",le="0.01",method="GET",status_code="200"} 9.0
http_request_duration_seconds_bucket{handler="jupyter_server.base.handlers.PrometheusMetricsHandler",le="0.025",method="GET",status_code="200"} 9.0
http_request_duration_seconds_bucket{handler="jupyter_server.base.handlers.PrometheusMetricsHandler",le="0.05 …
```
> Add a traitlet to disable recording HTTP request metrics

- jupyter_server/serverapp.py
Follow up to https://github.com/jupyterhub/jupyterhub/pull/4864
Add a couple of code comments to explain signal handling under JupyterHub to assist any future developers working on server shutdown.
Note, the issue #4864 fixed could cause orphaned subprocesses (e.g. kernels) to be left behind in some situations when they should have been killed.
> add comments to explain signal handling under jupyterhub

- examples/simple/simple_ext1/handlers.py
- jupyter_server/gateway/managers.py
- jupyter_server/services/contents/handlers.py
- jupyter_server/services/sessions/handlers.py
- pyproject.toml
This catches error when starting a kernel for a session (for example if one switches the kernel for an existing notebook), and propagate the error. Otherwise the frontend will just show "Error: uncaught exception".
In addition this setup ruff G001 – do not use string formatting in logging, see some of the reasons to not do that:
https://docs.astral.sh/ruff/rules/logging-string-format/
And fixes the few instances where jupyter-server does it.
> Better error message when starting kernel for session.

- pyproject.toml
This matches
https://github.com/ipython/ipykernel/pull/1277/commits/947894b8c0f52cc1ecbfb1600f27112ee1632445, and there doesn't seem to be a sensible alternative at the moment.
Fixes: #1475
> Ignore unclosed sqlite connection in traits

- jupyter_server/extension/handler.py
- tests/extension/mockextensions/__init__.py
- tests/extension/mockextensions/app.py
- tests/extension/test_app.py
- tests/extension/test_handler.py
avoids rendering errors or incorrect URLs for error pages, which must use the base static_url function
closes #1434
A probably cleaner approach would be to attach `static_url` to jinja environment globals instead of a method on the Handler, but the compatibility implications of switching to that are more complicated than I felt comfortable tackling.
> extensions: render default templates with default static_url

- jupyter_server/serverapp.py
Currently jupyter-server always uses `http://127.0.0.1:8888/?token=TOKEN` as the local URL. This changes it to use `[::1]` if jupyter-server is configured to listen on an IPv6 IP:
```
$ jupyter-server --ip=::
[I 2025-01-26 13:55:09.642 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-01-26 13:55:09.657 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-01-26 13:55:09.660 ServerApp] Serving notebooks from local directory: /tmp/test
[I 2025-01-26 13:55:09.660 ServerApp] Jupyter Server 2.16.0.dev0 is running at:
[I 2025-01-26 13:55:09.660 ServerApp] http://HOSTNAME:8888/?token=TOKEN
[I 2025-01-26 13:55:09.660 ServerApp]     http://[::1]:8888/?token=TOKEN
[I 2025-01-26 13:55:09.660 ServerApp] Use Control-C to stop this server and …
```
> If ServerApp.ip is ipv6 use [::1] as local_url

- jupyter_server/services/contents/manager.py
It's confusing that the .so files are hidden. They appear, for example, when compiling Python code, and it becomes unclear that the compiled files will be executed because Jupyter gives the impression that they don't exist. There is [an issue on GitHub](https://github.com/jupyter/notebook/issues/7409) and a [question on Stack Overflow](https://stackoverflow.com/questions/78260388/jupyter-lab-file-explorer-not-showing-so-files).
This PR removes .so files from the default list.
> Don't hide .so,.dylib files by default

- docs/source/developers/extensions.rst
- examples/simple/pyproject.toml
- jupyter_server/extension/application.py
- jupyter_server/extension/manager.py
- jupyter_server/serverapp.py
- tests/extension/mockextensions/app.py
- tests/extension/mockextensions/mock1.py
- tests/extension/test_app.py
- tests/test_serverapp.py
> Add async start hook to ExtensionApp API

- CONTRIBUTING.rst
- docs/source/api/jupyter_server.auth.rst
- docs/source/api/jupyter_server.base.rst
- docs/source/api/jupyter_server.extension.rst
- docs/source/api/jupyter_server.files.rst
- docs/source/api/jupyter_server.gateway.rst
- docs/source/api/jupyter_server.i18n.rst
- docs/source/api/jupyter_server.kernelspecs.rst
- docs/source/api/jupyter_server.nbconvert.rst
- docs/source/api/jupyter_server.prometheus.rst
- docs/source/api/jupyter_server.rst
- docs/source/api/jupyter_server.services.api.rst
- docs/source/api/jupyter_server.services.config.rst
- docs/source/api/jupyter_server.services.contents.rst
- docs/source/api/jupyter_server.services.events.rst
- docs/source/api/jupyter_server.services.kernels.connection.rst
- docs/source/api/jupyter_server.services.kernels.rst
- docs/source/api/jupyter_server.services.kernelspecs.rst
- docs/source/api/jupyter_server.services.nbconvert.rst
- docs/source/api/jupyter_server.services.rst
- docs/source/api/jupyter_server.services.security.rst
- docs/source/api/jupyter_server.services.sessions.rst
- docs/source/api/jupyter_server.view.rst
The following updates are made to [the contributing page ](https://jupyter-server.readthedocs.io/en/latest/contributors/contributing.html#setting-up-a-development-environment). 
1. During building the docs, errors related to non availability of `sphinx` can happen. New instructions are added to install this package ~~and its related dependencies~~
2. Changed format for the line `pip install hatch hatch run docs:build` to reflect it properly
3. Added double quotes which were missing for some commands like `pip install ".[docs]"` and `pip install ".[test]"`
> Update Contribution Page for Jupyter Server

- jupyter_server/auth/identity.py
- jupyter_server/serverapp.py
This fixes the issue  #1479 . 
Ran a grep across the files under jupyter_server and found 2 occurrences to fix by adding format().
> Fix for #1479 : Incorrect usage of i18n format

- docs/source/operators/security.rst
Addresses #1428 .
Updated the **Security in the Jupyter Server** page with content from the changes in [this PR ](https://github.com/jupyter/notebook/pull/4642).
The updated section looks like below now.
> Update Security Section in the Jupyter Server Documentation

- .github/workflows/downstream.yml
Recent released commit in Jupytext (https://github.com/mwouts/jupytext/commit/cb96a90be548856662685467587cec4566ad78ca#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R59), introduced `black` as requirement for their functional tests.
Even though `--ignore=tests/functional/others` is set, `pytest` will import the whole test suite during the test gather phase, thus requiring `black`.
In this MR, we update the `package_spec` to grab all dependencies required for the `test` and `test-functional`.
> tests: install test-functional requirements for Jupytext downstream tests

- docs/source/developers/websocket-protocols.rst
The doc didn't state that a WebSocket message has to start with the number of offsets, while the implementation was relying on that: https://github.com/jupyter-server/jupyter_server/blob/2cf8ac5b2bc2aa6aeb14a6e3f56230c160604b4b/jupyter_server/services/kernels/connection/base.py#L54-L61
> Update websocket-protocols documentation to reflect implementation

- README.md
The old one leads to an issue from 2023; IMO we can link to hackmd directly as it is linked in team compass.
> Update meetings notes link and zoom link

- jupyter_server/services/contents/fileio.py
To address #1502 avoid calling `shutil.copyfile()` and creating a`tmp_path` if the source file is not writable.
> Check file permissions before making tmp file

- jupyter_server/services/contents/filecheckpoints.py
- jupyter_server/services/contents/fileio.py
- tests/services/contents/test_fileio.py
This PR improves compatibility in environments where the working directory is read-only but the file isn't.
- **atomic_writing fallback**: If the parent directory is not writable but the file is, fall back to direct write instead of using atomic write with a temp file.
- **Checkpoints**: If the `.ipynb_checkpoints` directory is not writable, redirect checkpoints to a temp path:  
`$TMPDIR/jupyter_checkpoints/<rel_path>`.
This ensures writing and checkpointing continue to work smoothly in restricted or non-standard setups.
> Fallback to direct write for readonly dirs and use temp path for checkpoints

- jupyter_server/serverapp.py
2.15.0 behaviour:
```
$ jupyter-server --ip=127.0.0.1
[I 2025-01-26 13:29:02.002 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2025-01-26 13:29:02.026 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-01-26 13:29:02.030 ServerApp] Serving notebooks from local directory: /tmp/test
[I 2025-01-26 13:29:02.031 ServerApp] Jupyter Server 2.15.0 is running at:
[I 2025-01-26 13:29:02.031 ServerApp] http://127.0.0.1:8888/?token=TOKEN
[I 2025-01-26 13:29:02.031 ServerApp]     http://127.0.0.1:8888/?token=TOKEN
[I 2025-01-26 13:29:02.031 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2025-01-26 13:29:02.034 ServerApp] 
To access the server, open this file in a browser: …
```
> display_url: Don't duplicate public_url and local_url if they are the same

- jupyter_server/auth/identity.py
- jupyter_server/services/api/handlers.py
- tests/services/api/test_api.py
Fixes #1514 
This PR adds a new `PATCH` method to the api handler, to allow users to update their identity values. This handler is associated to a `update_user` method in the `IdentityProvider`, to effectively change the values.
The fields that can be updated is an attribute of the `IdentityProvider` class, and can contain all the attributes of `User` except `username`. By default only the `color` can be updated.
The `PasswordIdentityProvider`, which is the default identity provider, allows updating all the fields (except the username).
> Allow user to update identity values

- CHANGELOG.md
- jupyter_server/kernelspecs/handlers.py
- jupyter_server/nbconvert/handlers.py
- jupyter_server/services/contents/handlers.py
Hopefully fix https://github.com/jupyter-server/jupyter_server/issues/1539
> Fix the failing "Test Lint" check on CI

- jupyter_server/extension/manager.py
Motivated by https://github.com/jupyter-server/jupyter_server/pull/1521.
Supercedes #1522.
Adds a logger to the `ExtensionPoint` API.
This is fully backwards compatible, so should be fairly easy to review and merge.
> Add a logger to the ExtensionPoint API

- jupyter_server/base/handlers.py
- tests/base/test_handlers.py
Add check_origin check during check_xsrf_cookie for files.
Details: https://github.com/jupyter-server/jupyter_server/issues/1459
This PR addresses a CORS bypass vulnerability in the /files endpoint. The issue allows attackers to bypass
configured CORS restrictions (allow_origin_pat) by exploiting the XSRF token validation flow.
The current check_xsrf_cookie() method in base/handlers.py:537 only calls super().check_xsrf_cookie() (Tornado's
XSRF validation) without first checking if the request origin is allowed. This allows attackers to:
1. Set an XSRF cookie in a shared domain
2. Make cross-origin requests with matching XSRF tokens
3. Access /files endpoints despite CORS restrictions
- Impact: Unauthorized access to server files
- Exploitability: Requires shared domain configuration but …
> CORS is not checked when browsing files. check origin now https://github.com/jupyter-server/jupyter_server/issues/1459

- CHANGELOG.md
- jupyter_server/services/kernels/kernelmanager.py
- pyproject.toml
Fixes https://github.com/jupyter-server/jupyter_server/issues/1531
This PR uses [`typing.override`](https://docs.python.org/3/library/typing.html#typing.override) in favor of the [`overrides`](https://pypi.org/project/overrides/) dependency when possible. As of Python 3.12, the standard library offers `typing.override` to perform a static check on overridden methods. 
Currently, `overrides` is incompatible with Python 3.14. As a result, any package that attempts to import `overrides` using Python 3.14+ will raise an `AttributeError`. An [issue](https://github.com/mkorpela/overrides/issues/127) has been raised and a [pull request](https://github.com/mkorpela/overrides/pull/133) has been submitted to the GitHub repo for the `overrides` project. But the maintainer has been unresponsive.
To …
> Use stdlib override when possible

- docs/source/operators/configuring-logging.rst
- jupyter_server/log.py
- jupyter_server/serverapp.py
- tests/test_log.py
Fixes https://github.com/jupyter-server/jupyter_server/issues/1536
Currently the extra param keys do not replace the default set of keys, to avoid altering the current behavior by mistake. Instead they are added to the current set of param keys.
> Allow specifying extra params to scrub from logs
