jupyter-server/jupyter_server

- jupyter_server/extension/application.py
- jupyter_server/extension/tests/test_extension.py
I started writing the initial unit tests for the `ExtensionApp`. The tests exposed a few ways to better arrange methods in this class. 
The tests are quite simple. No servers are started. This mostly checks that configuration is loaded properly between extension and server.
> [MRG] Adding tests for ExtensionApp

- jupyter_server/extension/application.py
Because there is (intentionally) no default value and extension_name
is not a configurable trait (not sure that's the right terminology),
the @validate decorator won't be called.  This change fixes up the
validate function and adds a call to it during extension initialization.
Also raise ValueError rather than the base Exception if no value
is given (via the @default decorator).
> Fix extension_name validation

- jupyter_server/serverapp.py
> Add `--no-browser` flag

- jupyter_server/base/handlers.py
> Fix TrailingSlashHandler

- jupyter_server/serverapp.py
- jupyter_server/tests/test_extensions.py
Porting this PR by itself, because it was a bit tangled.
> Porting Notebook #4376

- jupyter_server/serverapp.py
I guess this is a leftover from the notebook code.
> fix: launch browser was using old notebook_dir

- README.md
Mention weekly meetings and roadmap on the README.
> readme: link to weekly meeting and roadmap

- README.md
GitHub actions seems more stable for our tests.
> Use github-actions build badge instead of travis

- docs/source/changelog.rst
- docs/source/frontends.rst
- docs/source/index.rst
- docs/source/migrate_from_notebook.rst
A few updates to the documentation in preparation or release 0.2.0
> Update docs for 0.2.0 release

- jupyter_server/prometheus/metrics.py
Quick terminology change in the Prometheus metrics file.
> Rename Jupyter Notebook Server to Jupyter Server

- CHANGELOG.md
Update changelog to backport in #167
> add v0.2.1 to changelog

- jupyter_server/serverapp.py
> Don't launch a browser just if there is a file to run

- README.md
Jupyter's Zoom channel has changed to: https://zoom.us/my/jovyan
> Update Zoom link of README

- docs/doc-requirements.txt
- docs/environment.yml
Updated the docs environment to pull all packages from `pip`. `jupyter_client` on conda is outdated and broke the build.
> update doc requirements

- jupyter_server/base/handlers.py
- jupyter_server/extension/handler.py
- jupyter_server/extension/serverextension.py
- jupyter_server/gateway/managers.py
- jupyter_server/serverapp.py
@kevin-bates That's about half of them, I'll do a separate PR for the rest.
> Fix exception causes in 5 modules

- .github/workflows/main.yml
- examples/simple/pytest.ini
- examples/simple/setup.py
- examples/simple/tests/test_handlers.py
- pytest.ini
This add pytest for the simple example and add 2 additional steps in the GitHub Actions: install the example deps + run the example tests.
> Add some test for the examples and run them in the GitHub Actions

- jupyter_server/extension/manager.py
- jupyter_server/extension/serverextension.py
Fixing a small issue with enabling extension that haven't previously been enabled/disabled.
> enable new extensions

- MANIFEST.in
There are a few missing items from the `MANIFEST.in`.
Fixes #266 and part of #267.
> add missing files to manifest in

- jupyter_server/extension/application.py
- jupyter_server/extension/handler.py
Addressing issues raised in https://github.com/jupyterlab/jupyterlab_server/pull/118.
> make static_url_prefix configurable

- MANIFEST.in
Ensure nested static content is published to pypi so the favicons are availble on install
cc/ @blink1073
> Ensure nested static content is published to pypi

- jupyter_server/templates/login.html
- jupyter_server/templates/page.html
> Add a minimal login page with info

- jupyter_server/extension/manager.py
Change `add_extension` to return boolean describing if the extension was successfully added.
> Handing broken extensions

- jupyter_server/pytest_plugin.py
Address the handling of nbconvert templates that were breaking applicable tests.
> Fix setup of nbconvert templates

- jupyter_server/extension/serverextension.py
Fixes https://github.com/jupyter/jupyter_server/issues/317
> Fix --user flag

- tests/test_utils.py
Consider removing cast_unicode in the future?
> Remove unused imports

- RELEASE.md
- jupyter_server/_version.py
This change updates the release instructions in RELEASE.md and adjusts the dev version string to be conformant.
> Update release instructions and dev version

- jupyter_server/serverapp.py
Port of jupyter/notebook#4999.
> Add setting to disable redirect file browser launch

- CHANGELOG.md
Also removes some outdated language of the changelog format.
> add changelog for pending 1.2.3 release

- jupyter_server/terminal/handlers.py
Backport of jupyter/notebook#4180
> Fix for the terminal shutdown issue

- jupyter_server/auth/security.py
Backport of jupyter/notebook#5078
cf jupyter-server/jupyter_server#110
> Ensure jupyter config dir exist

- jupyter_server/gateway/managers.py
https://github.com/jupyter/notebook/pull/6026
> Correct 'Content-Type' headers

- jupyter_server/serverapp.py
Port of jupyter/notebook#5941
jupyter-server/jupyter_server#110
> Re-enable support for answer_yes flag

- .github/workflows/codeql-analysis.yml
cf jupyterlab/team-compass#125
> Add Appropriate Token Permission for CodeQL Workflow

- .github/workflows/check-release.yml
Update link check regular expressions
> Update check-release workflow

- .github/workflows/check-release.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/integration-tests.yml
- .github/workflows/python-linux.yml
- .github/workflows/python-macos.yml
- .github/workflows/python-windows.yml
- CONTRIBUTING.rst
- README.md
- docs/source/developers/extensions.rst
- docs/source/index.rst
- jupyter_server/serverapp.py
> Update branch references

- setup.cfg
cf https://github.com/jupyter-server/jupyter_server_terminals/issues/5
> Pin pywintpy for now

- jupyter_server/services/kernels/handlers.py
> Fall back to legacy protocol if selected_subprotocol raises exception

- .github/workflows/downstream.yml
Let's at least make sure our other checks pass before making a minor release.
> Skip nbclassic downstream tests for now

- jupyter_server/extension/application.py
- jupyter_server/serverapp.py
- jupyter_server/services/contents/filemanager.py
- tests/extension/test_app.py
This reverts commit 9711822e157bd2ff2d4f8abe4c12a013223230e0.
> Revert "Server extension paths (#730)"

- .github/workflows/python-tests.yml
- .pre-commit-config.yaml
- Use the pre-commit CI service job
- Remove `jsonschema` check that was failing on the service
> Remove redundant job and problematic check

- .pre-commit-config.yaml
Restore `jsonschema` check and skip on pre-commit CI.
> Skip jsonschema in CI

- docs/source/contributors/team-meetings.rst
Update links for Roadmap and meetings archives
> Update team meetings doc

- .github/workflows/check-release.yml
- .github/workflows/integration-tests.yml
- .github/workflows/python-tests.yml
- README.md
- docs/README.md
- docs/source/developers/extensions.rst
- docs/source/index.rst
> Update branch references and links

- pyproject.toml
> Add license metadata and file

- jupyter_server/gateway/managers.py
- tests/test_gateway.py
(cherry picked from commit ee40dbc985e45f5c2699626e0f8f350b7f4989ac)
> Backport PR #896 on branch 1.x (Notify ChannelQueue that the response router thread is finishing)

- jupyter_server/base/handlers.py
- jupyter_server/extension/manager.py
- jupyter_server/services/kernels/kernelmanager.py
- tests/extension/test_app.py
(cherry picked from commit cb9c5edff77c2146d0e66425a82c7b6125b5039e)
> Backport PR #922: Improve logging of bare exceptions etc.

- docs/doc-requirements.txt
- docs/environment.yml
- readthedocs.yml
Pin mistune for compatibility with docs environment.
> Fix docs build

- jupyter_server/utils.py
> Don't validate certs for when stopping server

- .github/workflows/integration-tests.yml
- .github/workflows/python-tests.yml
> Remove hardcoded client install

- .github/workflows/python-tests.yml
- jupyter_server/services/kernels/handlers.py
- jupyter_server/services/kernels/kernelmanager.py
- tests/services/kernels/test_api.py
- tests/services/sessions/test_api.py
Counterpart to https://github.com/jupyter/jupyter_client/pull/845
> Handle client 8 pending kernels

- .github/workflows/python-tests.yml
- pyproject.toml
- Also add more checks to rollup check
> Fix min version check again

- .pre-commit-config.yaml
cf https://github.com/python-jsonschema/check-jsonschema/issues/183#issuecomment-1314521617
> use recommended github-workflows checker

- .github/workflows/python-tests.yml
- examples/simple/package.json
Match the ones used in JupyterLab
> Update example npm deps

- docs/source/operators/public-server.rst
That part of the documentation seems like a leftover from classical notebook.
> Remove frontend doc

- docs/source/developers/extensions.rst
> Fix broken link in doc

- jupyter_server/services/sessions/sessionmanager.py
Reverts jupyter-server/jupyter_server#1341
> Revert "Update kernel env to reflect changes in session."

- docs/source/developers/architecture.rst
> typo: ServerApp

- jupyter_server/config_manager.py
> Don't crash on invalid JSON in page_config (#1403)

- jupyter_server/services/kernels/kernelmanager.py
> Fix handling of missing parent header in record activity
